### ISSUE TITLE
icons list empty

### ISSUE THREAD

**Issue by muhasturk** [keremciu/sketch-iconfont#1]
I've installed plugin however list of icons is empty.

![](http://s28.postimg.org/vzl3ead4t/Screen_Shot_2015_09_14_at_12_01_29.png)

Sketch 3.3.3
OSX 10.10.5

**Comment by keremciu** [comment]
You have to install material icons font to see them. You can find the links of the icon-fonts just below the dependencies section in readme file.

For material icons:
https://github.com/google/material-design-icons/blob/master/iconfont/MaterialIcons-Regular.ttf

**Comment by keremciu** [comment]
@muhasturk Is it fixed your problem?

**Comment by muhasturk** [comment]
Yes thank you.
