### ISSUE TITLE
Icons added to random point on canvas

### ISSUE THREAD

**Issue by katywebster** [keremciu/sketch-iconfont#10]
Hi there,

Thanks for your excellent, useful plug-in.  The plug-in doesn't seem to recognise if you have an artboard selected when you insert an icon, and it places the icons on a random location on the canvas. It can make it very tricky to locate the icon, especially when they are quite small!

Apologies if this is the incorrect way of letting you know this - I'm not a developer, just a Sketch 3 user :-)

Regards,
Katy

**Comment by keremciu** [comment]
Hi Katy,

Thanks for your nice words. you're right, we can find a nice way to add icon to good point but I don't know what will be best solution about it? Add it to the center of the artboard as big? now we add it as 14px, it's a regular font size in the web. Maybe we can add a config file to plugin to choose font-size and the point? I will research about it, if you have any suggestion, it would be nice.

**Comment by Arkkimaagi** [comment]
Btw, 14px is not the regular size of the body text in web. 16px is

Anyways, a config option would be nice. (But most importantly a format to have my own svg icons supported)

**Comment by katywebster** [comment]
Hi keremciu,

Thanks. In my opinion, positioning the icon at the top left, or centre of the selected artboard would be useful. As long as it's always in the same place, users would get used to its' behaviour. And possibly making the font size slightly bigger would help too. A config file would be the ideal option I guess.

Thanks again,
Katy

**Comment by damenleeturks** [comment]
Would it be possible to just paste it in the center of the view (horizontally and vertically)?

**Comment by keremciu** [comment]
Hey guys,

I've an update now. Now you can add your icons to the center of the selected artboard.

It's a quick update it is not a stable solution. I will add a config file for the stable version because we have another solutions one of them when you add an ion, sketch will zoom to the added icon but I'd like to do that an option in config file.

I hope you will like it new update.
