### ISSUE TITLE
Changing default icon color doesn't work

### ISSUE THREAD

**Issue by miguelsolorio** [keremciu/sketch-iconfont#101]
When changing the default icon color in Configuration, if it's not set to #000000 then any other hex will import the icon font as white.

**Comment by keremciu** [comment]
hello @miguelsolorio 

Oh, sorry, that could be a problem about new Sketch algorithm, I was using red colours, they're working but other hex codes not working like you mentioned. I will try to fix that

```
c = this.hexToRgbPercent(color);
color = MSColor.colorWithRed_green_blue_alpha(c.r,c.g,c.b,c.a);
```
