### ISSUE TITLE
Installing font doesn't display all icons

### ISSUE THREAD

**Issue by aungsitnaing** [keremciu/sketch-iconfont#102]
I install the Fontawesome 4.7 using svg format. When I try to insert font, it doesn't display all icons. It only display 91 icons. Fontawesome have 675 icons.

**Comment by keremciu** [comment]
@aungsitnaing are you using their SVG file? it is problematic you can find the details in old issues. You should needs to build your own SVG by fontello or icomoon 

http://recordit.co/wy5ihqjPml
