### ISSUE TITLE
Missing font

### ISSUE THREAD

**Issue by Sototsylvain** [keremciu/sketch-iconfont#104]
Hi, i have a little problem with the Materialicons font.
I'm working on a project who i used this one.
Today i have a message with missing font.

i reinstalled it in my font library and reinstall the bundle with iconfont.
Everytime i try to open the sketch file, i always have the same message with missing font.
I deleted all my fonts on linotype and iconfont, but it still the same thing.

Someone have an answer ?
Thanks in advance

**Comment by keremciu** [comment]
hello @Sototsylvain 

can you give me any screenshot about your iconlist and the error? I need to see something to say true examples

Cheers,
Kerem

**Comment by Sototsylvain** [comment]
Hi, I finally managed to put back the typo, the problem does not come from the plug-in.
I have removed all fonts and I have recovered another version, and it all works.
There could be a conflict with the typo in download.

![capture d ecran 2017-02-21 a 14 31 19](https://cloud.githubusercontent.com/assets/25907354/23166852/86912f68-f842-11e6-87f4-680ff2312577.png)

**Comment by keremciu** [comment]
@Sototsylvain Oh I got it now, 

that was an old problem
https://github.com/keremciu/sketch-iconfont/issues/68
