### ISSUE TITLE
Did I install the plugin wrong?

### ISSUE THREAD

**Issue by studiog88** [keremciu/sketch-iconfont#105]
I watched all of the videos and carefully read the installation instructions.

I was able to open a grid and see the actual fonts — Material, IonIcons, FontAweseome, etc from the installed bundles.

But when i click on an icon absolutely nothing happens. The grid disappears and there is no font placed anywhere in my file.

I am using the latest Sketch version.

Any help would be great.

Thanks
Francesco //

**Comment by keremciu** [comment]
Hello @studiog88 

are you using sketch-autolayout plugin? if you are using that one you should update it

**Comment by itsdebbiee** [comment]
I've been having this same issue today as well. It's worked fine for me in the past. My Sketch is up to date, and I am not using the sketch-autolayout plugin.

Thanks,
Debbie

**Comment by itsdebbiee** [comment]
Never mind, I uninstalled the plugin and reinstalled it and it works fine now.
