### ISSUE TITLE
MaterialIcons-Regular vs. material

### ISSUE THREAD

**Issue by brant454** [keremciu/sketch-iconfont#107]
This is an awesome plugin! I had previously been using Font Book to copy/paste the icons into Sketch so the bonus of having this with search feature will be super efficient.

I know that the topic of material icons has been discussed a few times. I'm curious if there's a way to use Google's version of the font. I can imagine that there would be instances where multiple designers share time in a source file while using this plugin or not. If the fonts are different, it would create conflict.

I tried replacing the font in the plugin to use MaterialIcons-Regular and it created an issue. I'd be happy to do the swap myself if you could point me in the right direction.

Thanks in advance,
Brant

**Comment by keremciu** [comment]
Hello Brant,

first of all thank you so much for your nice comments, nice to hear them.

Yea, it is a big problem for me, if you use Google's version of the font you can't search... Maybe I can try to find a new way for this case with new version, I will consider that. If they use a nice Font Generator to build their font files, it will fix this problem. what I do without this solution will be a `hack`

In my workflow, we're using the `convert icons` command to share our files without conflicts.

https://github.com/keremciu/sketch-iconfont/issues/68

Cheers,
Kerem

**Comment by brant454** [comment]
Thanks for the response, Kerem. I'll keep an eye on the communication here to see if a fix is ever available.

**Comment by Kosai106** [comment]
Just checking in to see if there's been any changes in regards to this?

I'm personally experiencing issues by having both fonts installed and active at the same time. _(Either I can see the webfont from Google and not have working icons in Sketch, or vice versa.)_
