### ISSUE TITLE
[Feature] Provide Official Support to Instal & Updates via Sketchpacks

### ISSUE THREAD

**Issue by luxlogica** [keremciu/sketch-iconfont#108]
Please provide official support for [Sketchpacks](https://sketchpacks.com/) - this is a project that deserves it. It allows the Sketch plugin developer to keep all their users automatically updated, with no work from their part - updates are delivered automatically from your GitHub repo, when you push to your 'master' branch. 

Please have a look their [integrations page](https://github.com/integration/sketchpacks-relay), so we can get not just automatic version numbering, but also **auto-updating** working! - see image below of a plugin that has already enabled it.

<img width="717" alt="screen shot 2017-03-25 at 12 44 34 pm" src="https://cloud.githubusercontent.com/assets/2994472/24318489/6877702e-115a-11e7-9f7b-d309884919d9.png">

Right now, searching for this plugin in Sketchpacks yields these 2 results...:

<img width="721" alt="screen shot 2017-03-25 at 12 59 33 pm" src="https://cloud.githubusercontent.com/assets/2994472/24318535/f58326b6-115a-11e7-9a47-90ce74f73143.png">

**Comment by keremciu** [comment]
hello @luxlogica 

many thanks for your attention, I gave them the permission it works like a charm! that's so nice

I'm grateful for your guide :)

<img width="571" alt="screen shot 2017-03-26 at 21 12 16" src="https://cloud.githubusercontent.com/assets/1593488/24333889/f0b891ca-1268-11e7-8690-f65e7f373fbd.png">
