### ISSUE TITLE
Fontawesome SVG only showing a few fonts in Grid view

### ISSUE THREAD

**Issue by guzforster** [keremciu/sketch-iconfont#109]
Hi, when I install the SVG file of fontawesome it only shows some icons in the grid view, out of the 675 available. Is there something more that I should be doing for this to work?

**Comment by guzforster** [comment]
Hi, thanks for replying! I installed Fontawesome in my computer, the font is working fine. In Icon Font, I only installed Fontawesome font file (SVG). Shouldn't it work only installing individual fonts? Btw, when I install the  SVG font for the first time in the plugin, this config window appears - as a designer I have no idea of that means, so I just leave it blank (attached)...
![screen shot 2017-03-31 at 11 51 52](https://cloud.githubusercontent.com/assets/14154632/24543499/9304019c-1608-11e7-958d-896877602473.png)

**Comment by keremciu** [comment]
your case could be related your svg file of the font, can you try to install font-bundle? it could work.
