### ISSUE TITLE
Like it, but

### ISSUE THREAD

**Issue by mischugo** [keremciu/sketch-iconfont#11]
Isn't it easier to use Icon Jar to drag icons from into a Sketch document.
Works perfect for me, and easy to use.
If there could be a better integration to sketch... let me know :-)

Or did i misunderstand what iconfont is?

Regards, Maik

**Comment by keremciu** [comment]
We have alternatives IconJar, glyphsearch, etc. They're so awesome things. I'm always following them. I don't know an integration would be useful?

But yes, I'm trying to develop this plugin to better usage. If you have any idea, you can share it and also this is an open-source project, anyone can contribute and that would be so nice.

I hope we will do better.

**Comment by keremciu** [comment]
and also this plugin is not for only designers. I'd like to build a bridge between designers & developers to use icon-fonts.

**Comment by mischugo** [comment]
Ok, thanks a lot. It's really cool, but does not working fine for me.
The ion icons works, but the other not. Also, it's not possible to move the popup window :-(

I would like to have your plugin, but with a drag and drop feature like icon jar does. May be a litte bit better as icon jar does. So, let me individual any icon size in the icon grid window. Then drag or double click any icon to get the icon on the artboard with the size i have set :-)
May be the same with a color picker inside the grid window :-)))

Would be nice, or not?

Cheers

**Comment by KennySing** [comment]
+1 for double click to add

**Comment by keremciu** [comment]
@mischugo You can add an icon with one click now! :) @KennySing
