### ISSUE TITLE
Replacing icon no longer works

### ISSUE THREAD

**Issue by rijk** [keremciu/sketch-iconfont#111]
Since the latest Sketch update, I can no longer replace an icon by selecting it and then going to `Plugins > Icon Font > Grid Insert > [library]` and clicking an icon. This used to work.

**Comment by rijk** [comment]
Actually, it seems placing in general doesn't work anymore :D

**Comment by keremciu** [comment]
@rijk hello, can you send me a screencast? it could work, I can't reproduce your problem it is working with 39012

**Comment by charlesarvin** [comment]
it is not possible to select/mark text, and enter the icons via the plugin. what works is to select a textlayer (without selecting the actual text inside of it) and choose an icon afterwards.

when i create a new text layer in sketch via 'cmd+t' the text is pre-selected. therefore it would probably be a bit more intuitive to make it able to drop icons on selected text – if thats possible.

**Comment by rijk** [comment]
Here's a screencast! https://www.youtube.com/watch?v=A6UuXJeTJgo

**Comment by rijk** [comment]
Oh shoot, I just discovered I was on an outdated version of the plugin (4.3.0)! I did not figure out you have to update these manually. Just updated to the latest and it works again. Sorry for the false alarm!

**Comment by rijk** [comment]
And keep up the great work by the way, it's an awesome plugin :)
