### ISSUE TITLE
Installing fonts

### ISSUE THREAD

**Issue by UXDesignerNL** [keremciu/sketch-iconfont#112]
In the plugin menu it says "Install a Font [SVG]", maybe call it differently? As what you have to select is a .ttf file? Because I've tried with a font that had a .svg file as well, but that wouldn't make sense to select.

**Comment by keremciu** [comment]
@UXDesignerNL are you trying to select a ttf file? it is not working, I can read only SVG files to build a list of icons

you should install ttf file to your osx, install svg file on plugin
