### ISSUE TITLE
[Docs] Please Add Instructions on How to Install via Sketch Plugin Manager

### ISSUE THREAD

**Issue by luxlogica** [keremciu/sketch-iconfont#115]
The **[Sketch Plugin Manager](https://mludowise.github.io/Sketch-Plugin-Manager/)** is an amazing project, combining the best of all plugin managers that came before it:

* it is a normal Sketch plugin, that works inside Sketch's own 'Plugins' menu - i.e., it is not a separate app, and does not instal obtrusive menu items in your menubar.
* it provides a beautiful, searchable, easy-to-use interface for users to find the plugins they need.
* it automatically instals plugins listed in Sketch's official plugin directory, straight from the plugin's GitHub repo, requiring **no configuration** or special setup at all from the developer.
* it automatically advises users when a plugin needs updating, and updates them automatically with a single click.
* it provides the user with an easy-to-find, clickable link to your plugin homepage/GitHub repo.
* it can uninstall plugins with a single click, too.

The instructions that your users would need in order to instal Sketch Icon Font via [Sketch Plugin Manager](https://mludowise.github.io/Sketch-Plugin-Manager/) are:

``` markdown
Installation via [Sketch Plugin Manager](https://mludowise.github.io/Sketch-Plugin-Manager/):

1. In the 'Catalog' tab of the Sketch Plugin Manager window, click in the 'Search' field and type 'Icon Font', to filter the list.
2. You will see the 'Use Sketch Icon Font' plugin listed at the top of the list. Click the 'Instal' button inside it.
3. Install a font containing an svg font file, or install a font bundle - such as the one provided here: https://github.com/keremciu/font-bundles
```

Adding these instructions would greatly help popularise and support the project.

**Comment by keremciu** [comment]
hello @luxlogica , can you send me a PR? I'd like to see your commit, that would be nice
