### ISSUE TITLE
Unable to load fonts

### ISSUE THREAD

**Issue by ShiloRune** [keremciu/sketch-iconfont#118]
Hello,

After downloading the Sketch plugins manager and updating to your newest version, the fonts will not load. I've been using your plugin successfully prior. 

- I have tried installing the fonts again. No success.
- I tried uninstalling your plugin, and reinstalling. No success.
- I removed the plugins manager, and uninstalled your plugin again. No success.

Important to note the fonts have been verified in Font Book.

Any tips?

Thanks

**Comment by ShiloRune** [comment]
Looks like your last release was in November? Confused why the plugins manager prompted an update...

**Comment by keremciu** [comment]
@ShiloRune is it working?

**Comment by ShiloRune** [comment]
@keremciu Nope, any tips?

**Comment by ShiloRune** [comment]
@keremciu got it fixed :)

**Comment by keremciu** [comment]
@ShiloRune nice to hear that :) when you feel uncomfortable about setup progress you can watch this video http://recordit.co/2PMTB04Jav
