### ISSUE TITLE
Doesn't work in Sketch 45

### ISSUE THREAD

**Issue by ipolikarpov** [keremciu/sketch-iconfont#119]
"Grid insert" inserts just an empty text layer
"The selected text layer uses a font which can't be found on your system"
But all fonts from font-bundle are installed

**Comment by keremciu** [comment]
hello @ipolikarpov 

thank you for you information, I will try to handle these problems tonight

**Comment by anthonycmain** [comment]
I concur the issue, was just about to post.

**Comment by invisiblehermit** [comment]
Yes, have the same issue

**Comment by keremciu** [comment]
@invisiblehermit @anthonycmain @ckeelers @lederer @ipolikarpov version 45 support added

**Comment by ipolikarpov** [comment]
@keremciu thanks! works perfect after update

**Comment by wolfgangwaha** [comment]
I once again have the issue described by @ipolikarpov in Sketch Version 46.2. Any suggestions to resolve the issue?

**Comment by keremciu** [comment]
@wolfgangwaha did you try to update?

**Comment by wolfgangwaha** [comment]
I think I figured it out in the end. Thx guys!

**Comment by keremciu** [comment]
@wolfgangwaha nice to hear, I'm workin' on a new version, hope you like it :)
