### ISSUE TITLE
Multi Icon Select

### ISSUE THREAD

**Issue by KennySing** [keremciu/sketch-iconfont#12]
Right now you can click and drag to select multiple icons. However, when you do this it only adds the upper left most icon in the selection.

Maybe allow for multi select to add with "Shift+click" and "command+click" functionality. 

...or don't allow for multi select at all.

![image](https://cloud.githubusercontent.com/assets/5393862/10517815/6cc7b1e8-7313-11e5-8f43-99fe75adee07.png)

**Comment by keremciu** [comment]
@KennySing I've tried it but multi select is not possible but we can add an icon with one click now.
