### ISSUE TITLE
Typeface not recognized

### ISSUE THREAD

**Issue by BrianHennessy** [keremciu/sketch-iconfont#120]
I am able to use Font Awesome with the cheat sheet, so it is installed correctly, but the plugin says that the font is not installed.
<img width="229" alt="screen shot 2017-06-28 at 2 37 45 pm" src="https://user-images.githubusercontent.com/24944304/27654293-c94e1510-5c0f-11e7-9527-0c9e24bcb99b.png">
<img width="232" alt="screen shot 2017-06-28 at 2 37 56 pm" src="https://user-images.githubusercontent.com/24944304/27654302-d38917b4-5c0f-11e7-99c9-c551f8d7074b.png">

**Comment by ckeelers** [comment]
This just happened to me too. It started occurring after I updated to Sketch v45.

**Comment by kksharma1618** [comment]
Same here. Plugin broke after updating to sketch v45.

**Comment by plancker** [comment]
Same here.

**Comment by jarkkoryt** [comment]
Same – temporary workaround is to create a text layer with the icon font you want to use, selecting the layer, and then inserting the icon.

**Comment by christianstclair** [comment]
@jarkkoryt thanks for that work around, I'm having the same issue.

**Comment by keremciu** [comment]
@plancker @jarkkoryt @christianstclair @kksharma1618 @ckeelers @BrianHennessy the plugin has a new update for v45 but I could not fix this one because plugin is not saying this I could not reproduce this problem, can you explain more with the new version of plugin?

**Comment by mollycr** [comment]
I was having the same issue and updating the plugin fixed it. I had to update it through Sketchpacks though, Sketch's built-in plugin manager didn't see that there was an update available.

**Comment by kaulandb** [comment]
@keremciu I was having the same issue but the new version of the plugin fixed it. For some reason the plugin did not update automatically, I had to uninstall and reinstall. But then everything worked as normal

**Comment by kaulandb** [comment]
@mollycr haha just saw your comment. Look like we had the same experience

**Comment by lkimizuka** [comment]
I ran into the same issue, tried to uninstall and re-install, and now can't install the font bundle, because the install-bundle dialog isn't recognizing the *.json's as valid files.
![screen shot 2017-07-10 at 8 53 12 pm](https://user-images.githubusercontent.com/3478362/28050310-d9d85f48-65b1-11e7-9ee6-c9589c961c29.png)

**Comment by keremciu** [comment]
@lkimizuka hey, you should select font-bundles-master, I hope it will work like this

**Comment by lkimizuka** [comment]
@keremciu - that totally worked, thanks!

**Comment by caraclara** [comment]
![screen shot 2017-08-15 at 10 41 03](https://user-images.githubusercontent.com/13855032/29310649-69f7b12c-81a6-11e7-9183-32e80adb53d0.png)
All the icons not showing up. latest tff installed and still having the issue

Is there something i can do?
