### ISSUE TITLE
bundles deleted with update:/

### ISSUE THREAD

**Issue by charlesarvin** [keremciu/sketch-iconfont#122]
updated this plugin via sketch runner and all bundles where gone :/

**Comment by keremciu** [comment]
@charlesarvin oh man, your bundle was a special one? or font-bundle? there is a logic missing here, I've a export bundle action for this update problem but it will going to be safe update from now :/ If I can help with your sketch files please explain more your bundle and what your workspace needs, I'll try to handle that

**Comment by keremciu** [comment]
@charlesarvin there is font-fixer about it, if you'd like to I can send you by mail
