### ISSUE TITLE
Installing your own font [SVG] - nothing happens

### ISSUE THREAD

**Issue by aliyua** [keremciu/sketch-iconfont#123]
Hi, 

could you please provide clear instructions for installing your own font via SVG files. I keep selecting this option and adding SVG files but nothing happens. How is it exactly supposed to work?

Thanks

**Comment by keremciu** [comment]
hello,

It is not gonna work with svg files, it needs to be svg font. there is a video http://recordit.co/wy5ihqjPml on readme file

how you can import you svg files to fontello then you will have svg font to install the plugin

cheers
