### ISSUE TITLE
Searching by word doesn't work

### ISSUE THREAD

**Issue by iKamikadze** [keremciu/sketch-iconfont#124]
<img width="712" alt="screen shot 2017-08-16 at 15 34 22" src="https://user-images.githubusercontent.com/22727412/29363392-7742c98c-8298-11e7-9142-833b6473cc62.png">
When I'm typing some word about icon it seems that I get icons what doesn't have any meaning about this word

**Comment by keremciu** [comment]
@iKamikadze it is all about Icon names from icon-fonts :/ I don't have any details about it maybe it could be a feature more detailed keywords about icons
