### ISSUE TITLE
Bug preventing plugin to work on High Sierra

### ISSUE THREAD

**Issue by oskarkrawczyk** [keremciu/sketch-iconfont#125]
Normally I wouldn't bother to post a bug report for OS' that's in beta, but since we're on beta7, which means we probably have just one beta left before it goes Gold Master. Also from what I know Sketch has patched issues for HS, which means that the bug preventing iconfont to work seems to be laying on the plugin's side.

Basically what happens is when I trigger **Grid Insert**, the window that should appear just doesn't. I believe it's there, invisible or 0x0, because the Sketch window is blocked until I hit ESC to close the invisible Grid Insert picker.

If there's a way I can debug or provide more info please let me know.

This plugin is essential for me to work on @jsfiddle UI, so I'll help as much as I can to get it working again on HS.

**Comment by oskarkrawczyk** [comment]
@keremciu I don't want to be pushy, I know this is open source, but HS is just a week away, would be a shame if people updated and found this plugin not working.

As mentioned before, if there's anything I can do to help pinpointing the issue, just ping me!

**Comment by keremciu** [comment]
@oskarkrawczyk I tried to fix that problem at weekend but it looks harder to find where is the problem, I hope I can fix it soon but don't worry, I'm workin' on it now

**Comment by keremciu** [comment]
I downloaded 47.1, 45415

on high sierra 10.13

it's working properly

I took a video about it http://recordit.co/yReGEDhrQn
