### ISSUE TITLE
Doesn't work with Sketch 46.2

### ISSUE THREAD

**Issue by stigmates** [keremciu/sketch-iconfont#127]
Hi,
Sorry but it seems not working with the latest Sketch version. Installed the plugin one, two, three times, same for bundle… I read all your advices, watched video, issues reports… Fed up…
I use Linotype Font explorer X to manage my fonts. i tried directly macOs fonts management library… 
I can't get any icon on my artboard.
What's wrong? driving me nuts!
Thx for help.

**Comment by keremciu** [comment]
hello @stigmates 

I have 46.2, it's working but if you have high sierra I'm trying to fix it 

Can you share a screenshot here?

Thanks

**Comment by febeling** [comment]
I have the same problem. Screenshot below. 
<img width="912" alt="screen shot 2017-09-14 at 16 17 27" src="https://user-images.githubusercontent.com/4313/30434769-53b87aac-9968-11e7-9bfb-49c5bd7355dc.png">

Note the size being very tiny. I will happily provide more info if that helps with analysis.

**Comment by keremciu** [comment]
@febeling Hello,

I think it looks like you don't have a typeface in your Font Book. You should install 'material' font to your system.

https://github.com/keremciu/font-bundles has material ttf file

**Comment by febeling** [comment]
@keremciu I used this font before, and when trying to install it, Font Book warns of duplicates.

**Comment by keremciu** [comment]
@febeling can I see your Font Book material fonts?

**Comment by febeling** [comment]
@keremciu not sure what you mean. Would you like a screenshot from Font Book?

**Comment by chsWeb** [comment]
I am having the same problem as @febeling  I also use Font Explorer to manage my fonts, however it was working just fine up until the latest release. Today, it stopped working all together when I updated Icons Plugin, along with 2 other plugins - via the "# new updates" notification that appears in Runner.

**Comment by chsWeb** [comment]
Deleted and reinstalled the icon font plugin, fonts, and bundle, per the video. I can now see "Material" and "Font Awesome," etc. appear in Runner, and I can use Plugins > Icon Font > Grid Insert > Material and chose an icon, BUT nothing appears on my dartboard. No icon is installed.

What's interesting is that when I launch Runner, it notifies me that there is "1 UPDATE" and when I click '1 UPDATE' it shows me that Icons has an update available. 

![screen shot 2017-09-15 at 5 05 59 pm](https://user-images.githubusercontent.com/873222/30503596-d789d4ae-9a38-11e7-8254-7eab931282a9.png)
AND
![screen shot 2017-09-15 at 5 11 02 pm](https://user-images.githubusercontent.com/873222/30503605-e06ad870-9a38-11e7-80ef-7b6a00c246f5.png)


Not sure why there would be an update if I just downloaded the most recent version? Either way, everything is installed correctly, but the icons are not inserting into Sketch 46.2 (44496).

**Comment by chsWeb** [comment]
Note, I tried installing the fonts via Font Book and Font Explorer. It has always worked fine in Font Explorer, and trying Font Book made no difference.

**Comment by sunnee5150** [comment]
+1. Same case as @febeling

**Comment by keremciu** [comment]
@chsWeb @sunnee5150 @febeling hey guys, I'm trying to figure out that problem, are you using HighSierra? I will send a fix about HighSierra this weekend but I'm not sure about your cases, so hard to define your problem for me

**Comment by febeling** [comment]
@keremciu plain Sierra, version 10.12.6 (16G29) here

**Comment by keremciu** [comment]
@febeling material font couldn't find by Sketch on your screenshot, is it same for other fonts? material had some update problems, if others are working properly, I can send it to you

**Comment by febeling** [comment]
@keremciu it's actually quite strange. I tried a couple times now, and it's inconsistent. I tried a FontAwesome icon, which didn't show either, then one showed, then I tried material again, this time it worked, and next it doesn't. 

I'll attach another screenshot: 

<img width="912" alt="screen shot 2017-09-16 at 00 36 05" src="https://user-images.githubusercontent.com/4313/30505821-5a332eda-9a77-11e7-8360-1982b84345cf.png">

So from six icons inserted, roughly half show. And it's the same glyphs either, the playlist-add didn't work earlier, I remember that specifically.

**Comment by bootle** [comment]
Hey just to note - I've got the same issue and nothing Ive tried seems to resolve (reinstalled the font bundle, fonts, plugin and the app).

MacOS 10.12.6

**Comment by chsWeb** [comment]
@bootle same here, reinstalled fonts, bundles, plugins and tried with and without Font Book and FontExplorer.

**Comment by keremciu** [comment]
@chsWeb 

I've been on holiday guys, I will try to reproduce that problem, it looks there is something broken about font selection, as a quick try it's working on last update but I'm trying to find it

**Comment by bootle** [comment]
Welcome back :) Yeah, just checked - it works for me now too!

**Comment by sunnee5150** [comment]
running Sierra 10.12.6....where are we on this issue?

**Comment by keremciu** [comment]
@sunnee5150 @bootle @chsWeb @febeling @stigmates 

I downloaded 47.1, 45415

on high sierra 10.13

it's working properly

I took a video about it http://recordit.co/yReGEDhrQn

**Comment by stigmates** [comment]
Hey,

I downloaded Sketch 47.1. Its' working now.

Best,

*Jean-Christophe Besson*
Directeur artistique
-
jcb@stigmates.design <mailto:jc.b@stigmates.design>
Tel. +33 (0)6 28 05 21 94
Skype : Stigmates Design
-
25rue du Château Landon
75010Paris

Le 14/10/2017 à 13:42, Kerem Sevencan a écrit :

**Comment by elliottregan** [comment]
I am seeing this same issue in Sketch 48.2, High Sierra 10.13.2.

It seems to be a problem with sketch, because I can't get the fonts to work at all. It keeps trying to convert the font to Lucida Grande.

**Comment by keremciu** [comment]
@elliottregan maybe it's all about not installed ttf files?

**Comment by aql11** [comment]
Hi, doesnt work for me as well. :( 
It used to work perfectly until the latest update.

Am on Sketch 48.2 on El Capitan. 
Have all the fonts installed - just that nothing happens n the canvas when i insert the icons. 


![screen shot 2018-02-13 at 11 33 37 am](https://user-images.githubusercontent.com/4798106/36132386-f191f8e6-10b1-11e8-9394-4958d12fdf02.png)
![screen shot 2018-02-13 at 11 35 45 am](https://user-images.githubusercontent.com/4798106/36132415-17e35db4-10b2-11e8-99c2-78590fdea86e.png)

**Comment by jarnot9** [comment]
Still not working for me either. I've gone back to copying and pasting icons from Illustrator.
