### ISSUE TITLE
sketch 46.2 Can not add custom iconfont

### ISSUE THREAD

**Issue by lemonweb** [keremciu/sketch-iconfont#128]
[fontello-7e77d3f0-2.zip](https://github.com/keremciu/sketch-iconfont/files/1332022/fontello-7e77d3f0-2.zip)
sketch 46.2 Can not add custom iconfont,after adding the custom iconfont svg file, nothing happens

**Comment by lemonweb** [comment]
This interface does not appear
<img width="598" alt="demo" src="https://user-images.githubusercontent.com/20622127/30846187-3443c770-a2c9-11e7-926a-4f0b7a330fe0.png">

**Comment by keremciu** [comment]
yea, I found @lemonweb highsierra has some problems about it

**Comment by keremciu** [comment]
@lemonweb I tried it on 47.1 and high sierra

it's working properly, I took a test video about it

http://recordit.co/7CzMcMMdw2
