### ISSUE TITLE
How can I add my own icon font (ttf file) to fontbundle?

### ISSUE THREAD

**Issue by prakvem** [keremciu/sketch-iconfont#129]
How can I add my own icon font (ttf file) to fontbundle?
Great plugin but how can I add my custom icon font file ttf to your plugin so that I can use my icons in sketch? or is it limited to use the one you provide (FontAwesome, Material Design Icons, Ion Icons, Simple Line Icons (@bohn002), Ant Design Icons)

**Comment by keremciu** [comment]
@prakvem hello there is no chance to add ttf files, we need one svg file

there is a video about custom icon fonts http://recordit.co/wy5ihqjPml

**Comment by prakvem** [comment]
Thanks @keremciu. It worked :)
