### ISSUE TITLE
Not working after upgrade to macOS 10.13 High Sierra (17A405)

### ISSUE THREAD

**Issue by slehmann36** [keremciu/sketch-iconfont#131]
When calling up any of the Icon Font windows (Plugins > Icon Font > *), Sketch seems to lock up and must be force-quit and relaunched. This issue started after upgrading my Mac to macOS 10.13 High Sierra (17A405).

Any ideas?..

**Comment by keremciu** [comment]
@slehmann36 I'm working on it

**Comment by keremciu** [comment]
did you try to delete icon-font from /Users/{YOUR_PC_NAME}/Library/Application Support/com.bohemiancoding.sketch3/plugins/ 

then try to install again? I fixed it like that it's working on 46.2, I'm trying to upgrade my sketch to 47 then I could fix if there is a problem

 @slehmann36

**Comment by keremciu** [comment]
I downloaded 47.1, 45415

on high sierra 10.13

it's working properly

I took a video about it http://recordit.co/yReGEDhrQn
