### ISSUE TITLE
plugins not work well with sketch[version 44.1] in macOs High Sierra 10.13.1

### ISSUE THREAD

**Issue by zcweng** [keremciu/sketch-iconfont#133]
plugins not work well with sketch version 44.1 in macOs High Sierra 10.13.1

after clicked [Plugins]->[Icon font]->[All insert ] . 
no any window visible. 
cannot do anything.

Expecting Fix :)

**Comment by swingywc** [comment]
@zcweng I just faced the same problem recently, and it can be fixed by updating the sketch version. Mine is upgraded to v47.1 and it works fine now. Hope it can help you ;)

**Comment by keremciu** [comment]
@zcweng I updated to v47.1 :/ unfortunately I don't have a chance to use v44.1, can you have any chance to update sketch? @omulet
