### ISSUE TITLE
Icons can not be recognized in macOS 10.13.1

### ISSUE THREAD

**Issue by hstdt** [keremciu/sketch-iconfont#134]
macOS 10.13.1, sketch 47.1, installed font bundle from https://github.com/keremciu/font-bundles.

![image](https://user-images.githubusercontent.com/10215098/33161481-bb795c92-d05e-11e7-882d-c0c2616225c8.png)

**Comment by keremciu** [comment]
@hstdt  hello, did you install ttf file to your fontbook?

**Comment by hstdt** [comment]
@keremciu  Solved..Thank you😆.

**Comment by keremciu** [comment]
@hstdt nice to hear, enjoy it ✌🏻
