### ISSUE TITLE
SKETCH 48 || Plugin no longer works

### ISSUE THREAD

**Issue by cairnchampagne** [keremciu/sketch-iconfont#135]
@keremciu keremciu

I'm on Sketch 48. This plugin just doesn't work anymore. I uninstalled, and re installed the new version [4.5.3].

STEP 1
----
![screen shot 2017-12-06 at 10 15 49 am](https://user-images.githubusercontent.com/25507541/33668690-7a29e710-da6e-11e7-9ec5-93de492d039c.png)

STEP 2
----
![screen shot 2017-12-06 at 10 16 36 am](https://user-images.githubusercontent.com/25507541/33668738-95738620-da6e-11e7-9837-8dad94757152.png)

STEP 3 [Icon appears in LAYERS but, nothing appears on the screen]
----
![screen shot 2017-12-06 at 10 17 07 am](https://user-images.githubusercontent.com/25507541/33668776-ab2773c8-da6e-11e7-93c3-b42d78798473.png)

**Comment by keremciu** [comment]
@danewesolko @cairnchampagne I'm trying to fix it immediately guys,

you can follow my updates
https://twitter.com/keremciu/status/938401810603274240

**Comment by danewesolko** [comment]
@keremciu awesome! thanks mate.

**Comment by cairnchampagne** [comment]
@keremciu Thanks!

Great plugin. I wish icon fonts worked a little differently in SKETCH but - what can you do?

**Comment by keremciu** [comment]
@cairnchampagne @danewesolko 

I updated the plugin guys, you can try it out.


- yes, we can talk about it in a session how it would be better, I've some ideas about a new structure, I will be thinking about how we can consider ideas together then improve this plugin!✌🏻

**Comment by keremciu** [comment]
@cairnchampagne @danewesolko @pronouncedJerry @ aimhighagency

BEFORE UPDATE:
If you have a custom-font-bundle please first export your font-bunde like this: http://g.recordit.co/oxABJWnBeT.gif

then after update you can install that font-bundle without losing your custom fonts

**Comment by prueklk** [comment]
I exported the old font bundle, re-installed the new update (like the gif), installed the old font bundle, and nothing worked. I still got an empty layer. 
I also removed everything (fonts and plugin) and re-installed everything again, but nothing worked. 
Now I can't use this plugin anymore. I wonder if it's because of the new update of Sketch or something.

**Comment by keremciu** [comment]
@prueklk sketch has a new version man, you should install the version 48

**Comment by prueklk** [comment]
Yes. I just realised that the new version of this plugin is not compatible with the old Sketch. Thank you for the new update anyway. 

The upcoming version of this plugin looks really promising though ;)

**Comment by keremciu** [comment]
@prueklk I'm so sorry about that, 

yes, you know we're only a plugin developers, not a maintainer of whole product. `legacy version support` is a hard thing to do. You should write everything in an order with too many conditions.

**Comment by keremciu** [comment]
@prueklk but if you'd like to fix this flow, you can write sketch team, 

like we're giving compatible version on our manifest file to Sketch application, like this:
https://github.com/keremciu/sketch-iconfont/blob/e80f8dc6c256ee968a63b4df4d902f04b4bbf2e8/iconfont.sketchplugin/Contents/Sketch/manifest.json#L83

They can warn you like "don't update the plugin, you're not using version 48"

**Comment by prueklk** [comment]
Thank you for the information. 

At the moment, until I update the Sketch, I can use the old version of the plugin which is alright for me.

**Comment by pronouncedJerry** [comment]
that worked. thank you for the quick turnaround!

**Comment by cairnchampagne** [comment]
@keremciu 

Worked for me. Thanks! That's a huge help.
