### ISSUE TITLE
Updated to Sketch 48.1 and can't get the plugin to work

### ISSUE THREAD

**Issue by jarnot9** [keremciu/sketch-iconfont#137]
have exported the bundle as per video, but did it AFTER update. Anyway to fix it? Or do I have to wait for next release?

**Comment by pjatx** [comment]
I'm having the same issue. Font bundles that were installed during the update are no longer available for use and trying to re-add the bundles doesn't do anything.

**Comment by Austinauth** [comment]
### Context:
I updated to version 48 and it broke the plugin.

### Solution:
I was able to fix the issue by navigating to the _Manage Plugins_ menu in Sketch.
![image](https://user-images.githubusercontent.com/6994218/33778247-868ef5b8-dc0d-11e7-91ba-22c564daee4a.png)

Once I did that I clicked the _Update_ button that was on the _Icons_ plugin to update the plugin to version `4.6.0`. (Update button not pictured because I already updated).
![image](https://user-images.githubusercontent.com/6994218/33778502-925e4118-dc0e-11e7-8947-994ce337d50b.png)

Then I reinstalled the font bundle found [here](https://github.com/keremciu/font-bundles), using the 
_Plugins_ > _Icon Font_ menu in Sketch.

![image](https://user-images.githubusercontent.com/6994218/33778468-5c1054b6-dc0e-11e7-9133-64120dc933dd.png)

That seemed to solve the issue for me. Hope this helps!

**Comment by jarnot9** [comment]
Plugin shows that it's updated to 4.6.0, and I've tried to install the bundle, but it doesn't load. Did you put the fonts in your Font folder? Does location matter? All my icon fonts are installed according to Font Book. 

I found a work around by installing the .svg version of the font. It's time-consuming, though.

![sketch015](https://user-images.githubusercontent.com/25624977/33779035-1bfac450-dc00-11e7-91b7-a3967ee4079a.png)
![sketch014](https://user-images.githubusercontent.com/25624977/33779036-1c1286bc-dc00-11e7-9eb3-66d7eb5c10e3.png)

**Comment by jarnot9** [comment]
![sketch016](https://user-images.githubusercontent.com/25624977/33780088-43667828-dc04-11e7-9913-241aee7a9fce.png)

Sadly, it does not work for all icon fonts.

**Comment by Austinauth** [comment]
> Plugin shows that it's updated to 4.6.0, and I've tried to install the bundle, but it doesn't load. Did you put the fonts in your Font folder? Does location matter? All my icon fonts are installed according to Font Book.

I did not. I just downloaded the font bundle, made sure they were all installed on my machine, and selected the font bundle through the plugin in Sketch. The font bundle folder was in my Downloads folder.

**Comment by jarnot9** [comment]
Me, too. Still not working for me.

**Comment by rymorgan** [comment]
This is really stupid, but I was having the same problem after updating sketch. Plugin was up to date and I'd got to try and reinstall the font bundle and nothing would happen. Then I restarted my computer and restarted sketch and it's working again. Worth a shot.

**Comment by jarnot9** [comment]
No dice.

**Comment by keremciu** [comment]
@rymorgan @jarnot9 @Austinauth @pjatx 

Guys, I'm trying to figure out the problem, will write here soon it if needs an update

**Comment by keremciu** [comment]
@rymorgan @jarnot9 @Austinauth @pjatx 

Are you selecting the right folder to install a font-bundle? you can find that how can you select the right folder on the video http://recordit.co/2PMTB04Jav

**Comment by keremciu** [comment]
if you're using High Sierra, maybe it would be related with it, I will try to reproduce with HighSierra tomorrow

**Comment by jarnot9** [comment]
Definitely selecting the right folder.

**Comment by pjatx** [comment]
I'm also definitely selecting the correct folder (on high sierra)

**Comment by keremciu** [comment]
@jarnot9 @pjatx I think it's related with HighSierra, today I will try to reproduce it on HighSierra

**Comment by jarnot9** [comment]
thanks @keremciu

**Comment by voxnbaker** [comment]
System Mac HighSierra 10.13.2, Plugin 4.6.0
Created font in icomoon and updated JSON file:
{
  "fonts" : {
    "Ionicons" : {
      "path" : "Ionicons.json",
      "container" : "<i class='icon ion-*****'></i>"
    },
    "material" : {
      "path" : "material.json",
      "container" : "<i class='material-icons'>*****</i>"
    },
    "FontAwesome" : {
      "path" : "FontAwesome.json",
      "container" : "<i class='fa fa-*****'></i>"
    },
    "simple-line-icons" : {
      "path" : "simple-line-icons.json",
      "container" : "<i class='icon-*****'></i>"
    },
    "anticon" : {
      "path" : "anticon.json",
      "container" : "<Icon type='*****' />"
    },
    "Misys-icon-font" : {
      "path" : "Misys-icon-font.json",
      "container" : "<Icon type='*****' />"
    }
  }
}

Added font JSON file to bundle folder and made sure naming is correct. All I get is this:
<img width="594" alt="screen shot 2017-12-28 at 12 38 04" src="https://user-images.githubusercontent.com/8582075/34411100-8505bdca-ebcc-11e7-85e3-e97a1a072ac8.png">

I've wasted 2 days on this, recreating font, redownloading from icomoon, install/uninstall plugin, restart... repeat. Still same result.

**Comment by keremciu** [comment]
@voxnbaker I didn't use Icomoon nowadays, I'm suggesting to use fontello, there is a video about it http://recordit.co/wy5ihqjPml

I will try to use Icomoon again to fix is there any problem

**Comment by voxnbaker** [comment]
I tried fontello also and got the same result. In fact now, the icon selector window doesn't even 'pop up' now. Does for FontAwesome etc. It's fine, I've created a Sketch file with all my custom font characters on it and I just copy paste individually so no need to use plugin. Thanks for replying though.

**Comment by voxnbaker** [comment]
I fixed it. Installed the SVG instead and now is working.

**Comment by keremciu** [comment]
@voxnbaker oh nice, that's really good to hear :) but you know it's hard to support all icon suppliers :( that needs hard work :/ sorry about your bad experiences, hope can improve it in the future

**Comment by voxnbaker** [comment]
Thanks for rapid response Kerem, especially over xmas holidays!
