### ISSUE TITLE
Cannot install new font from SVG

### ISSUE THREAD

**Issue by wamujlb** [keremciu/sketch-iconfont#139]
Hi Kerem,

In new version of your awesome plugin I cannot install new fonts from svg.

**Comment by keremciu** [comment]
Hello Wamujlb,

Can you take me a screen video about it? like you can do that with http://recordit.co

**Comment by wamujlb** [comment]
Hi. Sure,

Here is the link: http://recordit.co/XhUKqYbSQe

I have checked your code, there are no problem, in my `svg` everything is OK. The same attributes.

**Comment by keremciu** [comment]
@wamujlb it looks like SVG file, didn't produce properly, I'm using fontello.com for that.

Can you try to build a new SVG file with it?

you can grab how you can do that from this video: http://recordit.co/wy5ihqjPml

**Comment by wamujlb** [comment]
Hmm.. I have used `Fontastic` for generating this files. Ok, I will try your solution and let you know.
