### ISSUE TITLE
Remove Dropdown select method?

### ISSUE THREAD

**Issue by KennySing** [keremciu/sketch-iconfont#14]
Seems like the dropdown selection method is fairly useless. Scrolling through one icon at a time is pretty undesirable.

ion and awesome call the dropdown: Add with Dropdown
material calls it: Add with combobox

Maybe this method could be removed all together or at least moved to the bottom of the list. Add with grid should be the first

**Comment by keremciu** [comment]
So thanks Kenny comments are really helpful for me. I was so busy and now I'm trying to change this plugin and your suggestions will be completed.

It will have 3 command:

- All Icon-font combined radio list
- Seperated radio list
-- awesome
-- material
-- ion
-- ..
- Learn icon name

We will have only 3 command, I think it will be really good :)

**Comment by keremciu** [comment]
with new update, I've deleted unnecessary view. I'll develop it more but it works good now.

We've one command to learn icon name now, future we will have only one command for add icon with name.

**Comment by keremciu** [comment]
@KennySing I've changed menu of plugin, it looks really nice now, I hope you like it.
