### ISSUE TITLE
Could not use the plugin

### ISSUE THREAD

**Issue by sashabeep** [keremciu/sketch-iconfont#140]
Sketch version 47.
Maybe, related to OS High Sierra.
First, i was surprised that font bundle disappears, installed it again, i can select icons from grid, but inserted icon doesn't shown and font select box is grayed out. Fonts installed on the system from ttf-files folder. Also i tried to delete fonts and install it again with no effect.

![screen shot 2017-12-26 at 14 47 13](https://user-images.githubusercontent.com/5689796/34356133-474458c4-ea4c-11e7-805c-2be26c2b3633.jpg)

**Comment by keremciu** [comment]
unfortunately, we can't cover version 47, you should update it to 48 also update the plugin, it will work as you expect 

https://github.com/keremciu/sketch-iconfont/issues/135
