### ISSUE TITLE
Icon fonts won't display in Sketch

### ISSUE THREAD

**Issue by equusignis** [keremciu/sketch-iconfont#142]
I have reinstalled the plug in and the font bundle and it seems to work. However, when it is placed on the artboard, the typeface pull down is blank and I get the message below:
![screenshot 2018-01-17 10 35 57](https://user-images.githubusercontent.com/35539681/35060132-4b49989e-fb72-11e7-842b-baced4e6fae6.png)
I have looked for this issue but can't find a solution. Is this a plug in thing or a Sketch thing. I currently can't use any icons and it's driving me mad!

Thanks

**Comment by chsWeb** [comment]
I had a similar problem. Try removing all the icon fonts, remove the plug-in from sketch. Then, follow the install instructions again for the font bundles and plug-in.

**Comment by rcoproc** [comment]
I'm with same problem, I realize that the icon is inserted into the Artboard, but the source does not work properly.

The error is "The selected text layer uses a font which can't be found on your system.'
Sketch 46.2

OSx High Sierra 10.13.2

**Comment by jarnot9** [comment]
rcoproc it seems like you haven't installed the font. Double click on the *.ttf. It will open FontBook. Then click "Install Font".

**Comment by Metrodata** [comment]
I had a similar problem. I have reinstall all the font but it doesn't work. I can only fix it by typing anything first and add fonts by selecting it.

**Comment by keremciu** [comment]
@rcoproc @equusignis I think you didn't install ttf files to your system

@Metrodata can you share a screenshot how you can fix it by typing? I didn't get your case

**Comment by dipnaze32** [comment]
I have the same issue. Only solve by typing something and replacing it with insert font icon.

**Comment by emilsong** [comment]
![image](https://user-images.githubusercontent.com/1205903/37072919-bb460382-21fe-11e8-9f47-530915389616.png)

have the same issue.  reinstalled the plugin and the fonts but doesn't work.
version 46.2

**Comment by tranquan** [comment]
version 4.5.3 seems working ok to me. my sketch version is `47.1`
