### ISSUE TITLE
Searching an icon doesn't work anymore

### ISSUE THREAD

**Issue by DieEgg** [keremciu/sketch-iconfont#143]
Hi! I love this pllugin, but in the last days I'm getting some issues in using it.

I'm working on a project with the Material Icons set. I'm not able anymore to use the 'search' function when I'm in the grid view (Grid Insert > Material).
I'm noticing that now, whan I insert n icon, the label of its layer is not called for example "material-arrow-forward", but instead "<MOMethod: 0x60800c028640 : target=0x60000ceffe80{     created = 1;     id = "arrow_forward";     name = "arrow_forward";     unicode = e82e; }, selector=name> - material".

I've tried to re-install the font, the bundles, the plugin, but nothing changed.
I'll attach two screenshots here :) 

![screenshot 2018-02-27 13 16 14](https://user-images.githubusercontent.com/9444697/36728274-77af6db4-1bc0-11e8-9066-f44f8e4f8e49.png)
<img width="356" alt="screenshot 2018-02-27 13 16 30" src="https://user-images.githubusercontent.com/9444697/36728275-77cb93ea-1bc0-11e8-8e90-5e485dc3c61e.png">

**Comment by dsuriano** [comment]
**+1**

Investigating a bit further via the Console.app, I'm seeing a new error after attempting to search:
```
Exception: TypeError: icon.lowercaseString is not a function. (In 'icon.lowercaseString()', 'icon.lowercaseString' is undefined)

Info: {
    column = 35;
    line = 361;
    sourceURL = "/Users/user/Library/Application Support/com.bohemiancoding.sketch3/Plugins/iconfont.sketchplugin/Contents/Sketch/add_all.js";
    stack = "research@/Users/user/Library/Application Support/com.bohemiancoding.sketch3/Plugins/iconfont.sketchplugin/Contents/Sketch/add_all.js:361:35\n/Users/user/Library/Application Support/com.bohemiancoding.sketch3/Plugins/iconfont.sketchplugin/Contents/Sketch/add_all.js:754:49\n[native code]\nonRun@/Users/user/Library/Application Support/com.bohemiancoding.sketch3/Plugins/iconfont.sketchplugin/Contents/Sketch/add_all.js:801:41";
}
```

**Comment by rafaRound** [comment]
Same to me.
Currently on El Capitan 10.11.6 and Sketch v49
Any idea what is wrong? 
It is weird because other mates doesn't have the same problem

![img_2094](https://user-images.githubusercontent.com/37114971/37041596-dc9c6f6e-215c-11e8-8b4e-380178ecb05b.JPG)

**Comment by dsuriano** [comment]
@keremciu — any ideas as to why this is happening? I'd love to help get this fixed. I tried replacing `icon.lowercaseString` with `icon.toLowerCase()` and it just spits back the same error.

**Comment by keremciu** [comment]
@dsuriano @rafaRound @DieEgg @jeffwain 

I will look at this one tonight, it looks like a little one to fix

**Comment by dsuriano** [comment]
@keremciu Thank you!

**Comment by keremciu** [comment]
@dsuriano @rafaRound @DieEgg I don't know how it's done but it works like a charm rn. I'm using sketch 49.1 and the last version of the plugin

**Comment by dsuriano** [comment]
Using the same and still broken. Same console error.

**Comment by DoortoGate** [comment]
@rafaRound I have the same issue than you. Any updates @keremciu ? Thanks

**Comment by DoortoGate** [comment]
haha, that's a hardcore procedure! I will give it a try as well:)

**Comment by rafaRound** [comment]
Yes... anyway it was time to to update Mac OSX. Good luck!

**Comment by DoortoGate** [comment]
@keremciu Any updates on this? I did everything on my side, and nothing can fix it:// 
![screen shot 2018-04-16 at 09 50 20](https://user-images.githubusercontent.com/35662914/38796395-9f6b47fe-415b-11e8-8825-644692e72148.png)

**Comment by D-Hux** [comment]
Been having this same issue as well. Was working prior to sketch 49 update. I thought it was probably just broken with update but recently helped friend install and his works perfect. I tried uninstalling and reinstalling thinking that might help, but NOPE. Any word on this?

**Comment by DoortoGate** [comment]
No news so far:/

**Comment by keremciu** [comment]
ops, It's working for me but I'm not sure about why it's not working on your side, are you using sierra? I'm using HighSierra maybe it's related to that?

I will try to find a fix for this one. it looks we need a fallback code there for sierra?

**Comment by DoortoGate** [comment]
@keremciu  I'm using HighSierra:/ it's really weird. Thank you for helping and providing this amazing product.

**Comment by keremciu** [comment]
@DoortoGate ops, no idea then, do you have any error on console.app?

**Comment by jeffwain** [comment]
@keremciu An uninstall/reinstall of the plugin, then adding the SVG version of the (formerly) broken font fixed this for me. On High Sierra.

**Comment by oddjones** [comment]
Same problem here - new Mac, fresh install of sketch (v50.2) - is there an open ticket anywhere?
