### ISSUE TITLE
Update sketch 49

### ISSUE THREAD

**Issue by JeroenDeBruin** [keremciu/sketch-iconfont#144]
Hi,I updated to sketch 49 and seem to have the same issue with update to sketch 48: The plugin doesn't seem to be able to load the fonts

**Comment by keremciu** [comment]
@JeroenDeBruin hello, what's the problem can you explain it with more details? I just installed Sketch 49.1 and the plugin, it works as expected.

**Comment by jeffwain** [comment]
@keremciu The issue we have is that when you open any of the Insert dialogs to place an icon, a broken element is created. It drops an element on the page with no typeface selected, no color applied, and no size. You also can't manually change the Typeface to make an icon appear.

Grid Insert does still let you select a new icon correctly when you already have a text box placed with an icon inside.

**Comment by kikiniki1313** [comment]
Hello, I'm using Sketch 49.2. I'm new to Sketch and just found this awesome plugin but it seems that I can't Install any fonts. They are installed on my computer [High Sierra OS]. But when I open the Icon Font plugin from Sketch it only have the options to install a font bundle or instal font [svg]. When I click to install font bundle all .json files are disabled. The same with .ttf files. Is it an install problem with the new Sketch 49.2 or I miss something? Can you help. Thanks!

**Comment by kikiniki1313** [comment]
It was my fault. Sorry. I did it ;) Ignore my comment. Great plugin, by the way! Thanks.

**Comment by amithkanand** [comment]
![image](https://user-images.githubusercontent.com/6287145/38847453-a7767a44-41cf-11e8-841a-a55c76321427.png)
I see this when I am selecting Plugin>icon font>grid insert>font awesome. Am I missing something?
