### ISSUE TITLE
Doesn't work with Font Awesome Pro

### ISSUE THREAD

**Issue by xJSN** [keremciu/sketch-iconfont#149]
I can't get the grid insert to work with Font Awesome Pro. I've tried installing both the OTF and TTF fonts on my Mac and then installing via SVG in Sketch. When opening Grid Insert, all of the icons show as [?]. I can click on them and an icon will display on the artboard, but I have no idea what I'm selecting. I can still reference the AF Pro cheatsheet and type in the name or paste in the icon, but the usefulness of this plugin is now totally lost. Lastly, with Pro offering 4 weights/styles, Icon Font isn't able to discern the difference between them when installing, so they all show up as "fontawesome-pro". Icon Font was working very well for me with the free version of FA provided by the install bundle, so I'm bummed out that this isn't working for me.

**Comment by austinstudio** [comment]
There is a thread or two in the bundle section about it.

https://github.com/keremciu/font-bundles/issues/25

**Comment by keremciu** [comment]
https://github.com/keremciu/sketch-iconfont/issues/170
