### ISSUE TITLE
Not working / nothing happens

### ISSUE THREAD

**Issue by anaimi** [keremciu/sketch-iconfont#15]
Hey,

I installed the plugin and installed the three fonts but I don't see anything when I click on the plugin from the plugin menu. I tried installing it from Sketch Toolbox and through the manual process, same result. See image below.

![image](https://cloud.githubusercontent.com/assets/60501/10628536/77c10484-7794-11e5-9baf-bd73a510fd15.png)

Sketch 3.2.2 (9983)
OSX 10.10

**Comment by keremciu** [comment]
Hello Ahmed,

Yea, it's not working with 3.2.2 version sorry about that I try to fix it before but it's impossible you need to upgrade.

And also we've a new problem with 3.4 version, I will fix it in 3 days.
