### ISSUE TITLE
icons not loading

### ISSUE THREAD

**Issue by amithkanand** [keremciu/sketch-iconfont#150]
I can only see  question mark icon and not the actual icons. Did I miss anything while installation?

<img width="534" alt="screen shot 2018-04-16 at 11 38 12 pm" src="https://user-images.githubusercontent.com/6287145/38872526-75a9f71e-4221-11e8-943f-09b95e8476b7.png">

**Comment by marcosdipaolo** [comment]
me too, solution?

**Comment by marshalloram** [comment]
I'm experiencing the same thing, after installing your [font bundle](https://github.com/keremciu/font-bundles) I get ? boxes for all icons. What am I missing. Running Sketch 50.2 on Mac OS 10.13.5.

**Comment by ThadeuBrito** [comment]
same here :(

**Comment by ThadeuBrito** [comment]
I fixed here. we need to install the fonts on our machine. double click o ttf files and install them

**Comment by Jiangtaste** [comment]
@ThadeuBrito Thank you

**Comment by crytax** [comment]
didn't work for me, ttfs and bundles are already installed, it's the streamline icon bundle. when I select one empty box there are several icons added in a row in my sketch file, any other suggestions?

**Comment by marcosdipaolo** [comment]
You need to download the icons to your project and place them in the right directory

**Comment by hey-simone** [comment]
I installed them. Still having the same problem.
