### ISSUE TITLE
only half of the icons appear

### ISSUE THREAD

**Issue by fusun470** [keremciu/sketch-iconfont#158]
When I try to insert the iconfonts, only half of it appear. And the rest is the repetition of a grouped icons. Pls see the screenshot:
![screen shot 2018-07-26 at 1 04 51 pm](https://user-images.githubusercontent.com/15936078/43277058-db592308-90d4-11e8-81ff-c7c2b29d01ed.png)
... What could be the reason?

**Comment by mamuts12** [comment]
#170 commented there my method of fixing

**Comment by frankparadiso** [comment]
@mamuts12 maybe it is a font conflict?
It happens to me too with FA PRO and Free. 😏
