### ISSUE TITLE
Incompatible with Sketch 3.4

### ISSUE THREAD

**Issue by andrewhml** [keremciu/sketch-iconfont#16]
Isn't working with the latest Sketch Update. I've been able to place one icon upon document open, and then none of the commands work.

**Comment by twelch555** [comment]
I'm seeing the same behavior. You get one shot and then have to restart for the plugin menus to work again.

**Comment by dandooze** [comment]
Same here. Sketch Version 3.4 (15588)

**Comment by diegoiglesias** [comment]
Same here. It was happening too with Marvel plugin but it's been solved after their update a few hours ago.

**Comment by leifniem** [comment]
Same for me.

**Comment by saherwafai** [comment]
me too
