### ISSUE TITLE
Only three options available

### ISSUE THREAD

**Issue by mulihi** [keremciu/sketch-iconfont#160]
I installed Iconfont manually on Sketch, but it doesn't show up the options in the video. Especially I need the option to remove fonts. Please see the screenshot:
![bildschirmfoto 2018-08-07 um 14 35 08](https://user-images.githubusercontent.com/40860893/43776129-2f4ab782-9a4f-11e8-8335-2233d0a040bc.png)
Did I make anything wrong or whats the reason?
Thank you in advance,
mulihi

**Comment by mamuts12** [comment]
Did you select just the folder "fond-bundle-master" through Install a Font-Bundle?

Remove option only appears when u successfully add font or font bundle to icon font

**Comment by keremciu** [comment]
you just need to install a font-bundle or a svg font
