### ISSUE TITLE
icon font on sketch 51.2 is not available

### ISSUE THREAD

**Issue by hylahyla** [keremciu/sketch-iconfont#161]
Hi
I've already download the font and try to install a font bundle.
but nothing happened on my next step.
![2018-08-20 5 40 47](https://user-images.githubusercontent.com/42537491/44333029-35416180-a4a0-11e8-8ee8-ddce6e6867a3.png)
That's really weird.
My osx system is Mac OSHigh Sierra 10.13.6.

**Comment by keremciu** [comment]
@hylahyla 

Oh okay, it could be related to the plugin, let me try it

**Comment by hylahyla** [comment]
So sad that I still can not use it until now.

**Comment by keremciu** [comment]
@hylahyla there's no problem about this version

are you doing everything like this video? http://recordit.co/2PMTB04Jav

**Comment by raposorolo** [comment]
exact same is happening to me, @hylahyla are you sure it works with Sketch 51.2  and Mac OS High Sierra?
Thanks for your help

**Comment by keremciu** [comment]
@raposorolo I've the same versions, it's working, maybe you're choosing the wrong folder? can you look at the video please?

**Comment by cmarydai** [comment]
I'm having the same issue

**Comment by anhdq1801** [comment]
@keremciu 
Thank you for great plugin, but it now doesn't work with Sketch version 52.3. Could you check this.

Thanks

**Comment by anhdq1801** [comment]
Sorry it work when i choose parent folder :D of font bundles
