### ISSUE TITLE
Dark Mode Support

### ISSUE THREAD

**Issue by richardsteers** [keremciu/sketch-iconfont#165]
Search text & close icon is not visible when running dark mode in MacOS Mojave.

![screen shot 2018-10-09 at 11 22 03 am](https://user-images.githubusercontent.com/13160627/46640071-9e4a7900-cbb5-11e8-9ccd-68b54f7eecc4.png)

**Comment by ioTus** [comment]
Same as @ziyafenn - icons displayed as "?" and search not working. Imported fonts as SVG

![image](https://user-images.githubusercontent.com/5401162/47453187-f5894580-d780-11e8-9e4f-dee0f4de0be2.png)

**Comment by ioTus** [comment]
@ziyafenn solution for [?] icons: https://github.com/keremciu/font-bundles/issues/30
You have to edit the SVG file font ID to match the font-face font-family:

`  <font id="fontawesome-pro" horiz-adv-x="640">
    <font-face font-family="Font Awesome 5 Pro"`

becomes

`  <font id="Font Awesome 5 Pro Solid" horiz-adv-x="640">
    <font-face font-family="Font Awesome 5 Pro Solid"`


Dark theme incompatibility still exists

**Comment by keremciu** [comment]
ups kinda big issue to fix. I will try to give it a time on weekend

**Comment by keremciu** [comment]
I published a new version for dark mode, I will try to manage this font-awesome 5 issues in a different branch
