### ISSUE TITLE
if there is no match on search, I need to close window one time.

### ISSUE THREAD

**Issue by Koshukey** [keremciu/sketch-iconfont#166]
First, thanks for this helpful library for me, who use sketch❤️

 my suggestion💡
when I search icon and nothing matched, I need to close window one time.😮
I want add the future when I search icon and did not match, I can go back first icons page,
by clicking kinda home button.

![screen shot 2018-11-30 at 14 06 28](https://user-images.githubusercontent.com/31874274/49269620-345d9a00-f4a9-11e8-9da1-9a14db7cb46a.png)

**Comment by keremciu** [comment]
@Koshukey sorry for late response but yes, clearing search text functionality would be nice for the future but right now you can clear your text and enter again then you will return to first icons page
