### ISSUE TITLE
Can't see the query text when in dark mode. 

### ISSUE THREAD

**Issue by Himanshu-compucorp** [keremciu/sketch-iconfont#167]
I'm running on sketch 52.2 and everything is working fine. Just started using Font-Awesome Pro 5 without any problems. However, Now for some reason, I can't see the query string I type to search icons in the grid-insert box. It's working as hitting enter applies the search but not being able to see what's typed in is a pain. 

I have tried re-installing the plugin, restarting the sketch etc. I'm running on MacBook Pro and have dark mode enabled in Sketch if that helps.

**Comment by UXDesignerNL** [comment]
@keremciu please add dark mode support

**Comment by keremciu** [comment]
yes, I had the problem too,  I will look at this one how to solve it

**Comment by keremciu** [comment]
@Himanshu-compucorp @UXDesignerNL @SteveCostello @ruskakimov @aguavisual there's new version, fixes this thing
