### ISSUE TITLE
Icon Font stopped working in skech 52.6

### ISSUE THREAD

**Issue by xsubbu** [keremciu/sketch-iconfont#168]
Can't see any font bundle even after uninstalling &  installing multiple times 

<img width="1440" alt="screen shot 2019-01-20 at 12 18 29 pm" src="https://user-images.githubusercontent.com/11087858/51436151-85ba2680-1cad-11e9-9095-7eff32a776c1.png">

**Comment by keremciu** [comment]
hello @xsubbu did you choose the parent folder of your bundle folder?

**Comment by xsubbu** [comment]
i choose the folder titled "bundle" in the 'font-bundles-master' folder

**Comment by xsubbu** [comment]
any suggestions @keremciu, am feeling so crippled :s :)

**Comment by keremciu** [comment]
@xsubbu oh sorry for really late response, I was not available on GitHub, you need to choose `font-bundles-master` folder. I think if everything works like I planned there will be a new release without bundle-installation stuff.
