### ISSUE TITLE
Unicode code for the font is not saved in readable format for developers

### ISSUE THREAD

**Issue by mdonogma** [keremciu/sketch-iconfont#174]
Please can you assist- when adding the fonts to sketch the code of the font is not saved in a format we can read. Please can you indicate what encoding you used when wrong the font “Unicode” code to the object

Urgent

**Comment by keremciu** [comment]
can you share a screenshot for this one? it's hard to understand what's not readable

**Comment by mdonogma** [comment]
thanks so much for quick response.

attached is screenshot of the specific layers sketchapp JSON extract. Your addin creates the object and sets a "string" - the string is not eligible.
<img width="453" alt="image" src="https://user-images.githubusercontent.com/13458476/59344099-b714bb00-8d50-11e9-8956-b82193f40d42.png">

**Comment by mdonogma** [comment]
cab you confirm if the unicode from the Json is being saved into the "string" field.
<img width="615" alt="image" src="https://user-images.githubusercontent.com/13458476/59344502-8f722280-8d51-11e9-890d-d0db60e3a0b4.png">

**Comment by mdonogma** [comment]
extract from your ionics.json file.

<img width="407" alt="image" src="https://user-images.githubusercontent.com/13458476/59344540-a6187980-8d51-11e9-8937-e9d6307cd53f.png">

**Comment by mdonogma** [comment]
Any chance you figured out the issue? From what I can tell from javascript you are saving a code. We need the Unicode saved that matches your .json files Unicode

**Comment by keremciu** [comment]
yep but what would you like to have for developers? changing them into different format? I don't know if you convert them it will be named icon

**Comment by mdonogma** [comment]
Just plain text like : string: ef56

Exactly per your .json files Unicode values

No encoding just plain readable text.

Is this possible?

**Comment by keremciu** [comment]
yep it should be possible but it looks like a lot of work for a small challenge :/

**Comment by mdonogma** [comment]
If you can’t fix it can you at least tell me what you are saving into that string when you add it to sketch app? If I know the encoding I can try decode it.
How do you identify the icon when user selects icon details in sketch app?


Sent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by keremciu** [comment]
@mdonogma yep I'd like to help but I need to see the whole process you went through.

In the screenshot, If you change your text font to icon font-family then it will show the icon but you'd like to grab icon name from sketch file, right? I can give it a try about this, how about the name of the icon layer?

**Comment by mdonogma** [comment]
I only use the menu to insert new icon.
You plug-in creates new menu which pops up a dialog, I search for icon using your dialog then double click the one it should insert. It then inserts new icon onto the page.

I never start with existing text layer just insert new from your dialog.

Using the name isn’t the best as user could chane the name of the layer in sketch.

Your javascript appears to insert / assign a value to “string” when inserting the icon. Why not just ensure it is plain text when setting that value. 

How does your toolbar know which icon is selected when using show icon details from your menu option? It’s using something unique right? Not the name but something you’ve set when first adding the icon to the layer?

Really appreciate your help .

**Comment by mdonogma** [comment]
I think sketchapp is setting the value I showed in the screenshot. Sorry for wasting your time. I just need to figure out how to decode the hex from the Jobject 

Thx again

**Comment by keremciu** [comment]
It was hard to imagine the process, I'm sorry about couldn't help about this point but yes, I built this unicode check inside,
https://github.com/keremciu/sketch-iconfont/blob/master/iconfont.sketchplugin/Contents/Sketch/learn.js#L22

I hope you can find a good way to handle this stuff

@mdonogma

**Comment by keremciu** [comment]
I'm closing this while this is not related to the plugin
