### ISSUE TITLE
How to repackage the source files

### ISSUE THREAD

**Issue by mdonogma** [keremciu/sketch-iconfont#175]
Please can you indicate or provide link on how you pacakaged up the plugin.

There is a bug we found but need to know how to repackage plug-in. Did you use sketch package manage?

**Comment by keremciu** [comment]
@mdonogma hey, there's no packaging solution for this plugin but if you can give more details maybe I could help you

**Comment by mdonogma** [comment]
So how do you debug , fix then repackage?

Essentially need the Unicode values from your .ionic.json file to be saved on the sketch object so I can read it via sketch plugin or sketch app json export. I sent screenshot in previous ticket.


Sent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by keremciu** [comment]
https://github.com/keremciu/font-bundles/blob/master/bundle/Ionicons.json I still didn't get why this is requested but I'm closing this while that's not related to the plugin
