### ISSUE TITLE
Icon font make Sketch app crashed

### ISSUE THREAD

**Issue by Yomatsiya64** [keremciu/sketch-iconfont#176]
I've got this issue for a while now, Sketch support ask me to contact you directly. 
See my description below :

Sketch crash all the time after I try to modifiy the size of the icon font using the Text size panel. You need to do something about it, it's agreat plugin but this issue make it really anoying to use.

Regards.

**Comment by keremciu** [comment]
which version do you use?

**Comment by Yomatsiya64** [comment]
You mean which version of Sketch ? Or you talking about your icon font plugin ?

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by keremciu** [comment]
both would be better but I was asking Sketch version :) @Yomatsiya64

**Comment by Yomatsiya64** [comment]
Ok 😉
Sketch 58
Icon font 4.5.1

_


Yohann Lansot
Lead UX/UI designer  –  MATSIYA
___________________________________________________________________

Améliorez la performance
de votre entreprise

+33 (0)5 59 31 18 24 <tel:+33559311824>
www.matsiya.com<http://www.matsiya.com/fr/>


De : Kerem Sevencan <notifications@github.com>
Répondre à : keremciu/sketch-iconfont <reply@reply.github.com>
Date : mardi 8 octobre 2019 à 10:13
À : keremciu/sketch-iconfont <sketch-iconfont@noreply.github.com>
Cc : Yohann Lansot <yohann.lansot@matsiya.com>, Mention <mention@noreply.github.com>
Objet : Re: [keremciu/sketch-iconfont] Icon font make Sketch app crashed (#176)


both would be better but I was asking Sketch version :) @Yomatsiya64<https://github.com/Yomatsiya64>

**Comment by keremciu** [comment]
Oh I don't have Sketch 58 but let's see:

```Sketch crash all the time after I try to modifiy the size of the icon font using the Text size panel. You need to do something about it, it's agreat plugin but this issue make it really anoying to use.```

Can you share a screenshot what do you use to change the size of the icon? @Yomatsiya64

**Comment by Yomatsiya64** [comment]
Better than Screenshot, screen reccording attached
_


Yohann Lansot
Lead UX/UI designer  –  MATSIYA
___________________________________________________________________

Améliorez la performance
de votre entreprise

+33 (0)5 59 31 18 24 <tel:+33559311824>
www.matsiya.com<http://www.matsiya.com/fr/>


De : Kerem Sevencan <notifications@github.com>
Répondre à : keremciu/sketch-iconfont <reply@reply.github.com>
Date : mardi 8 octobre 2019 à 10:27
À : keremciu/sketch-iconfont <sketch-iconfont@noreply.github.com>
Cc : Yohann Lansot <yohann.lansot@matsiya.com>, Mention <mention@noreply.github.com>
Objet : Re: [keremciu/sketch-iconfont] Icon font make Sketch app crashed (#176)


Oh I don't have Sketch 58 but let's see:

Sketch crash all the time after I try to modifiy the size of the icon font using the Text size panel. You need to do something about it, it's agreat plugin but this issue make it really anoying to use.

Can you share a screenshot what do you use to change the size of the icon? @Yomatsiya64<https://github.com/Yomatsiya64>

**Comment by keremciu** [comment]
sorry but I can't see it here :/ @Yomatsiya64

**Comment by Yomatsiya64** [comment]
Any email where I can send you the record screen ?

_


Yohann Lansot
Lead UX/UI designer  –  MATSIYA
___________________________________________________________________

Améliorez la performance
de votre entreprise

+33 (0)5 59 31 18 24 <tel:+33559311824>
www.matsiya.com<http://www.matsiya.com/fr/>


De : Kerem Sevencan <notifications@github.com>
Répondre à : keremciu/sketch-iconfont <reply@reply.github.com>
Date : mardi 8 octobre 2019 à 11:21
À : keremciu/sketch-iconfont <sketch-iconfont@noreply.github.com>
Cc : Yohann Lansot <yohann.lansot@matsiya.com>, Mention <mention@noreply.github.com>
Objet : Re: [keremciu/sketch-iconfont] Icon font make Sketch app crashed (#176)


sorry but I can't see it here :/ @Yomatsiya64<https://github.com/Yomatsiya64>

**Comment by Yomatsiya64** [comment]
Hi, sorry for the delay.. here is a video to reproduce the bug.. 
[crash-icon-font-sketch-480p.mov.zip](https://github.com/keremciu/sketch-iconfont/files/3743511/crash-icon-font-sketch-480p.mov.zip)

**Comment by keremciu** [comment]
@Yomatsiya64 oh I didn't get this from your first comment here but this is not related to the plugin. Plugin just put some texts into your document, it doesn't affect your typography tool. This is definitely related to the Sketch :/ sorry I couldn't help about Sketch application
