### ISSUE TITLE
How i can add Material Design Icons

### ISSUE THREAD

**Issue by talehkarimli** [keremciu/sketch-iconfont#178]
Hey All,

I can't add Material Design Icons (https://github.com/Templarian/MaterialDesign-SVG) into this plugin. Maybe anyone can help me? @keremciu please help to me :). 

Thank you for this amazing project!

**Comment by keremciu** [comment]
I recommended him the video of custom icon-font import and it worked! anyone having the same issue can look at the video https://recordit.co/wy5ihqjPml
