### ISSUE TITLE
Plugin works only once per session

### ISSUE THREAD

**Issue by bennyp123** [keremciu/sketch-iconfont#18]
I can only use the plugin once per session. 
Meaning, if I activate the plugin, either by shortcut key or by menu item, I can select and insert my icon or icons (with grid mode) but once I've inserted icons, I cannot reactivate the plugin unless i first quit sketch. 

I'm using latest Sketch on El Capitan

**Comment by keremciu** [comment]
thanks Benny, I need to update my os to elcapitan after that I will check your problem

**Comment by saherwafai** [comment]
I installed the new sketch update and the plugin is not working again, the grid shows, but after you choose the new symbol it dosen't update in the document

**Comment by keremciu** [comment]
I will share the new version of this plugin tonight, I hope it will fix your problems. @saherwafai  @bennyp123

**Comment by saherwafai** [comment]
thanks a lot @keremciu

**Comment by keremciu** [comment]
Please try new version guys, it has nice updates :) @bennyp123 @saherwafai

**Comment by bennyp123** [comment]
Still seems I can't load the plugin twice in one session :/
```
05/11/2015 11:18:58.655 PM Font Awesome (Sketch Plugin)[3864]: TypeError: page. currentArtboard is not a function. (In 'page. currentArtboard()', 'page. currentArtboard' is 1.8753200613732316e-306)
line: 348
sourceURL: /Users/bennyp/Library/Containers/com.bohemiancoding.sketch3/Data/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Sketch Iconfont/iconfont.sketchplugin/Contents/Sketch/add_icon_grid.cocoascript
column: 44
```

**Comment by keremciu** [comment]
@bennyp123 I can't handle that problem, I think I need to update to el capitan but we've have an update for it now, can you try it?

**Comment by bennyp123** [comment]
```
06/11/2015 8:46:34.100 AM Sketch[56110]: Exception: TypeError: doc. currentPage is not a function. (In 'doc. currentPage()', 'doc. currentPage' is 1.8753200613732303e-306)
06/11/2015 8:46:34.100 AM Font Awesome (Sketch Plugin)[56110]: TypeError: doc. currentPage is not a function. (In 'doc. currentPage()', 'doc. currentPage' is 1.8753200613732303e-306)
line: 347
sourceURL: /Users/bennyp/Library/Containers/com.bohemiancoding.sketch3/Data/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Sketch Iconfont/iconfont.sketchplugin/Contents/Sketch/add_icon_grid.cocoascript
column: 39
```

**Comment by keremciu** [comment]
can you send me your details? which version of sketch are you using? and which osx? because normally you can't create a sketch file without a page :(

**Comment by bennyp123** [comment]
I was running sketch 3.4 but just caught the update to 3.4.1 between that update and your update, the problem seems to be solved. Great work!
