### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by Neema** [keremciu/sketch-iconfont#2]
Was a fan of your last plugin, so of course I'll be commenting on this one as well :stuck_out_tongue_closed_eyes: 

The current UI doesn't move. There is no way to drag that window. Anyway that could be possible?

![screen shot 2015-09-14 at 2 34 06 pm](https://cloud.githubusercontent.com/assets/1239557/9862431/b3cf4da0-5aed-11e5-8245-d94b54ca5d90.png)

Along with adding "Search" into this view, is it possible to either limit the number of selections (right now you can select multiple things) and only let people add one icon. Or what would be better, to be able to add multiple icons if you can select multiple.

**Comment by damenleeturks** [comment]
I just submitted a pull-request to fix the cut-off columns issue you mentioned above.

**Comment by Neema** [comment]
@damenleeturks looks nice! 
i also meant how currently you have the ability to click-drag to select and it allows you to select multiple icons...

**Comment by damenleeturks** [comment]
@Neema: I hadn't even noticed that. Does it insert multiple when you do that?

**Comment by keremciu** [comment]
I've a nice solution about it guys, can you try it? They're radio boxes now but I don't know how can we select multiple with command key but I think multiple add would be bad, we need to prevent it.
