### ISSUE TITLE
Request: add Linea iconset

### ISSUE THREAD

**Issue by heartfield** [keremciu/sketch-iconfont#21]
Request to add the Linea icon set from http://linea.io/ to the plugin.

**Comment by keremciu** [comment]
it has not an icon-font but yes, I can build a github repo for it. I'll try it.

**Comment by heartfield** [comment]
Thanks. The zip file provided on their website does contain .ttf icon-fonts. I'm not sure if this is exactly what you need for the Sketch plugin though.

**Comment by keremciu** [comment]
Hello @heartfield 

Now you can import it with svg font file!

https://github.com/keremciu/sketch-iconfont/tree/customfonts
