### ISSUE TITLE
Icons not showing up

### ISSUE THREAD

**Issue by danielkiedrowski** [keremciu/sketch-iconfont#23]
Hello,
I just got the plugin to run with 3.4.1 but there is still one problem. When opening up any of the icon collections it looks always like this:

![bildschirmfoto 2015-11-12 um 3 58 11 nachm](https://cloud.githubusercontent.com/assets/3187582/11121447/377fc620-8956-11e5-9f4d-fdb6674ceb72.png)
What am I doing wrong?
Thank you very much.

**Comment by keremciu** [comment]
Hello Daniel,

You need to install icon-fonts, you can find them below dependencies title.

> You need to install icon fonts to your OS:

> For fontawesome: https://github.com/FortAwesome/Font-Awesome/raw/master/fonts/FontAwesome.otf

> For ion icons: https://github.com/driftyco/ionicons/raw/master/fonts/ionicons.ttf

> For material icons: https://github.com/google/material-design-icons/raw/master/iconfont/MaterialIcons-Regular.ttf

@danielkiedrowski
