### ISSUE TITLE
sketch v3.4.2 / problem adding icon

### ISSUE THREAD

**Issue by geroldhinzen** [keremciu/sketch-iconfont#25]
icons could not be added correctly to stage in sketch v.3.4.2.

**Comment by keremciu** [comment]
what was the problem with it? I'm trying to add it and it works perfectly with sketch 3.4.2

**Comment by mhayes** [comment]
I'm noticing a similar issue in 3.4.2 ... adding icons seems to result in nothing happening. If I quit sketch and reopen however the plugin will work a few times before it stops again.

**Comment by keremciu** [comment]
Can you send me your log details about it on console? I can't handle your problem guys :(

@geroldhinzen @mhayes

**Comment by knilob** [comment]
I'm having the same issue. Here's what shows up in my Console for Sketch after I try to add an icon:

`11/22/15 10:48:40.563 AM Sketch[3167]: Ignoring autorelease call on NSShadow {0, 0}`

**Comment by mhayes** [comment]
@keremciu Not sure if this is helpful, but this is the only message I'm seeing in the console:

```
11/22/15 10:38:36.608 AM Sketch[27374]: Could not set the target and action on (
    "<NSButtonCell: 0x6000002f7a80>",
    "<NSButtonCell: 0x6000002e9400>",
    "<NSButtonCell: 0x600000eedf00>",
   ... (CONTINUES FOR A WHILE, OMITTED FOR BREVITY)
)
```

**Comment by keremciu** [comment]
Hello guys,
@mhayes @knilob @geroldhinzen 

I've updated the plugin can you reinstall it? and also I think it might be good to use sketch 3.4.3

**Comment by knilob** [comment]
Everything looks good on my end with the new version in Sketch 3.4.3. Thanks, Kerem!
