### ISSUE TITLE
Add multiple icons at same time

### ISSUE THREAD

**Issue by ninjaisun** [keremciu/sketch-iconfont#27]
Hi Keremciu,

The sketch-iconfont is a really good plugin. I use it everyday to add icons to my UI.

One thing I think it can be a enhancement here, when I add icon with the grid, I just can add one icon at once right? Then I need to open the gird again to add another one, so can I add multiple icons at same time? It can save much time for me, thanks.

**Comment by keremciu** [comment]
Hello,

Yea, I've tried it but I didn't find a good way for it. I'll update this plugin in two days after that I'll try it for you. I'd like to add a function for multiple colored icon.

**Comment by vicliu1990** [comment]
oh，  i really need  it  too
