### ISSUE TITLE
If  i  can  search in  Chinese language？

### ISSUE THREAD

**Issue by vicliu1990** [keremciu/sketch-iconfont#28]
Hi Keremciu,

I  am  in China
If  i  can  search in  Chinese language？

**Comment by keremciu** [comment]
Hello @vicliu1990 

I'll try it when I finish custom-icon support

**Comment by vicliu1990** [comment]
ok， if you are working on   Chinese language searching，  i can join and help

**Comment by vicliu1990** [comment]
![qq20151209-0 2x](https://cloud.githubusercontent.com/assets/8925514/11661987/8e185754-9e0f-11e5-8619-280ebc7aba26.png)

i can  help to  translation
