### ISSUE TITLE
what is wrong with this？

### ISSUE THREAD

**Issue by vicliu1990** [keremciu/sketch-iconfont#29]
![qq20151204-0 2x](https://cloud.githubusercontent.com/assets/8925514/11568306/58cfad50-9a26-11e5-92e9-7ae91a3103cf.png)

as above
i can not  see  these icons

i have  installed  thsi：For fontawesome: https://github.com/FortAwesome/Font-Awesome/raw/master/fonts/FontAwesome.otf

**Comment by keremciu** [comment]
Hello @vicliu1990 

I've updated the plugin, can you reinstall it?

**Comment by vicliu1990** [comment]
thks  very much：）

i  installed the  new  version，  it is ok now。
