### ISSUE TITLE
search only work once

### ISSUE THREAD

**Issue by billzhong** [keremciu/sketch-iconfont#31]
Hi,
When I search a keyword in add an icon box, it only works at first time.
If I type another keyword to search, always return empty.
I have to close the box and open again to search.
Can you take a look? Thanks.

**Comment by keremciu** [comment]
Hello @billzhong 

I've fixed it with new update you can use it endless times :)

**Comment by keremciu** [comment]
You can search endless times now with new update which is on new branch :)

https://github.com/keremciu/sketch-iconfont/tree/customfonts
