### ISSUE TITLE
Adding custom Shortcuts to Icon fonts

### ISSUE THREAD

**Issue by flytoe** [keremciu/sketch-iconfont#33]

**Comment by keremciu** [comment]
for commands?

like

Grid Insert > blabla (custom shortcut?)

I can do it if you want :)

**Comment by flytoe** [comment]
Yes that would be super nice

**Comment by keremciu** [comment]
I added this into my workflow. I hope I can finish it this weekend :)

**Comment by keremciu** [comment]
@flytoe with new version; you can add a shortcut for fonts now. I hope it helps you :)

**Comment by flytoe** [comment]
wow very nice thank you!

**Comment by faithhva** [comment]
Can I also change or add a shortcut once the font is installed?
