### ISSUE TITLE
Nothing happens after installation

### ISSUE THREAD

**Issue by Pym** [keremciu/sketch-iconfont#36]
So I installed the fonts from the font-bundles repository, the the plugin, then I launched Sketch and clicked on `Plugins > Icon Font > Install a Font-Bundle`. But after that, nothing happened.

I tried to quit/relaunch Sketch, still nothing.

Any idea? I'm using the latest beta: v3.5 (25125)

<img width="546" alt="screen shot 2016-01-13 at 14 23 14" src="https://cloud.githubusercontent.com/assets/89233/12295510/bffe628c-ba01-11e5-8696-2ff089e58eaa.png">

EDIT: I just tried again with the latest stable version and it's working.

**Comment by georgesofroniou** [comment]
I am also having issues, once installed via Sketch Toolbox when I click the plugin nothing happens?

**Comment by keremciu** [comment]
@georgesofroniou @Pym I need a console log to understand what is the problem. You can find the error log on Console.app.

**Comment by georgesofroniou** [comment]
@keremciu thanks for the response, I did an uninstall and a reinstall and it appears to of worked.

**Comment by keremciu** [comment]
@georgesofroniou welcome, I hope it helps you :)
