### ISSUE TITLE
Not working in Sketch Beta?

### ISSUE THREAD

**Issue by KokoDoko** [keremciu/sketch-iconfont#38]
After installing the fonts on El Capitan, and then installing the bundle from Sketch Beta 3.5, nothing happens. The fonts palettes do not become available.

**Comment by hardikpandya** [comment]
Same here. Is there a solution?

**Comment by keremciu** [comment]
so sorry for late response but I reinstall my os this week, I've tried with 3.5.2 now and its working? can you try it again @hardikpandya @KokoDoko

**Comment by KokoDoko** [comment]
It's working again, thanks!

**Comment by keremciu** [comment]
so nice, I hope it helps you :)
