### ISSUE TITLE
Name changes

### ISSUE THREAD

**Issue by damenleeturks** [keremciu/sketch-iconfont#4]
Can we change the name of a few of the plugin options and menu items so that they describe the UI that is displayed (rather than the code)? 

- Change `radiolist` / `list` to `grid` or `grid view`
- Change `combobox` to `drop-down list` or simply `list`

(Sorry, I don't remember the precise names of the current options; I'm submitting this from my phone and can't look them up easily.)

**Comment by Neema** [comment]
+1, Agree. Currently the "list" view is more of a Grid than a list...I think naming it a grid is more appropriate

**Comment by keremciu** [comment]
I'm changing but I'm not sure about them and also I think icon-fonts menu needs to be merged but I don't know how we can use too much icon-fonts in one view. I created a room in gitter, we can talk about there https://gitter.im/keremciu/sketch-iconfont
