### ISSUE TITLE
Weather SVG Font Rendering

### ISSUE THREAD

**Issue by jkhedani** [keremciu/sketch-iconfont#40]
I've attempted to install the following SVG font:

https://github.com/erikflowers/weather-icons

It follows the same html pattern as font awesome and appears to insert the character properly but in grid view doesn't display the icon preview. Just shows squares from a font called "Last Resort". Any way we can fix this?

<img width="1007" alt="screen shot 2016-03-05 at 3 50 15 pm" src="https://cloud.githubusercontent.com/assets/1855878/13551780/1d27f5fc-e2ea-11e5-9269-5300962cf967.png">

Great plugin, btw!

**Comment by keremciu** [comment]
Hello @jkhedani,

I've fixed the problem with this icon font, you can remove and reinstall this font, I hope it will work.

Thanks :)

**Comment by jkhedani** [comment]
Yup that fixed it. Thanks!
