### ISSUE TITLE
Placement of icons

### ISSUE THREAD

**Issue by larsenpedersen** [keremciu/sketch-iconfont#41]
In reference to #10:

I saw @damenleeturks talking about pasting icons in the center of the view  (horizontally and vertically) - Will this be possible in the future? - I'm working with quite lengthy artboards and have to scroll quite a bit in order to grab the icons from the center of the artboard :)

Btw. I love the plugin!

**Comment by keremciu** [comment]
hi @larsenpedersen,

So thanks for your thoughts, if I got it right, you'd like to add icons in the center of the view? I can do that but I need to try something first :) I hope I can develop it soon

**Comment by larsenpedersen** [comment]
@keremciu You got me right! - Icons appearing in the center of the artboard doesn't work, when your artboard is 2000px x 8000px :smile:

**Comment by keremciu** [comment]
@larsenpedersen 

If you'd like to use, I can add zoom function. when you add an icon, your screen will zoom to that, is it helps you?

I developed the zoom function but I do not build config for that :/

I'm trying view centered solution now

**Comment by larsenpedersen** [comment]
@keremciu Thanks for the offer, but the zoom function won't really help me - I still have to move the icons several thousand pixels :smile: 

Besides that, I can just do the zoom function by hitting `CMD` + `2` (or `CMD` + `3` for just centering around the icon).

**Comment by keremciu** [comment]
@larsenpedersen You need to reinstall the plugin then you can add an icon the center of the view :)

**Comment by larsenpedersen** [comment]
@keremciu It works like a charm! Thanks buddy! :smile:
