### ISSUE TITLE
Icon replacing other icon/text

### ISSUE THREAD

**Issue by larsenpedersen** [keremciu/sketch-iconfont#42]
If I add one icon and want to add another icons right after (without first deselecting the first icon), the second icon will replace/overwrite the first icon.

The same thing (obviously) happens if you got a textfield selected when adding an icon.

Sorry for the issues, @keremciu .

**Comment by keremciu** [comment]
@larsenpedersen and also If you select a empty textfield, you can fill it with an icon, I think if we change this, I need to change more things but If I can develop the new version of this plugin with sketch panels, I will add a config file for this :)

but now when you add an icon, first you need to deselect

**Comment by larsenpedersen** [comment]
Lets call this an enhancement then :)

**Comment by sogen** [comment]
TBH I like that it works this way 👍

**Comment by keremciu** [comment]
@sogen @larsenpedersen now we have a configuration command for this :) you can uncheck replace option on configuration to get this functionality
