### ISSUE TITLE
Uncertain about usage process

### ISSUE THREAD

**Issue by thecolab** [keremciu/sketch-iconfont#43]
This is a very nice plugin I used it on one machine and worked very well.
I just installed on my new machine and now the only menu items I see are about installing fonts. Even after installing I can't add icons like before.

I don't see any instructions so assuming it should just work as before but I can't seem to figure out if I did something incorrectly.
Please see below.
<img width="500" alt="screen shot 2016-03-14 at 9 14 34 am" src="https://cloud.githubusercontent.com/assets/4508574/13736395/363c9f48-e9c5-11e5-856e-8c5d0491304a.png">

**Comment by keremciu** [comment]
hello @thecolab 

thank you, I always to improve this plugin and yes, we don't have a good documentation about new features :/ I'm trying to write a documentation, I hope it would be good.

Did you install popular fonts bundle? https://github.com/keremciu/font-bundles you can install this folder with "Install a Font-Bundle" command.

If you have any different icon-font you can install it with "Install a Font" command, do not forget we are using only SVG files if your icon-font don't have any SVG file, you can't add it :/

And I'm trying to update this plugin I hope we will have SVG export command soon :)

**Comment by coolof** [comment]
I too have this problem. I have downloaded the bundles but I'm not sure what to do with them? I can't select them one by one through the _Install a Font-Bundle_ option. Selecting the entire folder closes the window but don't seem to do anything?

I also tried installing the Material Design iconfont manually using the latest version from (http://google.github.io/material-design-icons/)[http://google.github.io/material-design-icons/], installing the svg version as you mentioned above. This is the result I got:

![screen shot 2016-04-04 at 23 14 42](https://cloud.githubusercontent.com/assets/157721/14263517/5259dd1a-fabb-11e5-8978-331d217d9078.png)

All of this might be an errors on my part, I'm just not sure what I'm suppose to do?

**Comment by keremciu** [comment]
@coolof mm, did you install ttf font file to your osx?

**Comment by Tenkir** [comment]
I'm having this same issue. I installed font awesome, and it appears in fontbook, but I only see "Install Fonts" inside sketch.

**Comment by jaminroe** [comment]
@keremciu I would update your ReadMe to say something about installing the ttf files first, _then_ to use the plug-in. 😉

**Comment by keremciu** [comment]
hello @jaminroe I will try to rewrite readme file :) I don't change anything for a while because I'm developing the new version of this plugin, if you have any idea for the new version, we can discuss on gitter.im :)

**Comment by jaminroe** [comment]
@Keremciu cool!! Definitely will

**Comment by baconette** [comment]
I am using your font bundle and have installed the plugin and can't get pass "install font bundle" or "install icon font" it doesnt do anything. I had this plugin working perfectly until the update. 

I also can't find where to " add icon bundle"

**Comment by mrengy** [comment]
Using "Install a font" and selecting a .ttf file did nothing for me, but using "install a font" and selecting a .svg file made many other actions under "plugins" > "icon font" available.

**Comment by jrs-onforce** [comment]
I'm also seeing nothing happen with "Install a font".  No fonts become available in Plugins > Icon Font.

I installed the fonts (.ttf files) via the OSX font installer first.  Then "Install a font" from Plugins > Icon Font.  Tried restarting Sketch.  Uninstalling and reinstalling the plugin via Sketch Toolbox.

Nothing.

Sketch Version 39.1 (31720)

**Comment by keremciu** [comment]
@jrs-onforce @mrengy I'm developing the new version of the plugin, I will share two article with the new update. It will explain everything, the usage process would be precise and easy to understand :)

**Comment by keremciu** [comment]
@jrs-onforce If you'd like to use "install a font" command, you need to select SVG file of the icon-font, not ttf
