### ISSUE TITLE
Copy HTML isn't copying anything

### ISSUE THREAD

**Issue by jaminroe** [keremciu/sketch-iconfont#46]
When I click the _Copy It_ buttons, it's not copying anything to my clipboard. See my screencast:

![2016-04-15 15_24_46](https://cloud.githubusercontent.com/assets/1559447/14572700/32b918ca-031e-11e6-8144-d507bc6d0b34.gif)

**Comment by keremciu** [comment]
@jaminroe so thanks needs an update for that 🤔 are you using 3.7? I will try to update plugin this weekend for this 

I've caught that error
15/04/16 23:50:32,823 HTML of Selected Icon (Sketch Plugin)[22001]: TypeError: undefined is not an object (evaluating 'Library.widgets.clipboard')
line: 386
sourceURL: /Users/keremsevencan/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Sketch Iconfont/iconfont.sketchplugin/Contents/Sketch/learn.cocoascript
column: 24

**Comment by jaminroe** [comment]
Yup 3.7. That's the latest right? Sorry not at my computer now

**Comment by keremciu** [comment]
@jaminroe yep, so sorry it was really bad mistake for me 😪 I've fixed with this https://github.com/keremciu/sketch-iconfont/commit/89a08fae005b6db0c5fbe0fa244fe0420e1304f3

**Comment by jaminroe** [comment]
Haha no problem! Appreciate the plugin. It's very cool and useful!
