### ISSUE TITLE
Option to add "Converted to outlines" version with bounding box

### ISSUE THREAD

**Issue by joshmtucker** [keremciu/sketch-iconfont#47]
First off, thanks a ton for this plugin! Use this every day, very frequently.

One thing that would be amazing is the option to have the added icon (from the dialog) be converted to outlines and have a bounding box added as a layer below it automatically. 

Not everyone I work with has the fonts installed so when I share documents, it shows up as all question marks. I prefer to work with the vectors as well, but keep a maintained bounding box. What I do today is convert the icon to outlines, add a base at the bottom so I can maintain the container, and then folder it. I included a screenshot.

I would do a pull request if I knew enough about how to write in Cocoascript – maybe soon!

Cheers!
![screen shot 2016-04-19 at 10 37 03 am](https://cloud.githubusercontent.com/assets/6194928/14649232/f73ba056-061a-11e6-803e-13d2c478e9f9.png)

**Comment by keremciu** [comment]
@joshmtucker so thanks for your nice comments, I'm really glad to hear that 😊

I think that's really good idea. I'm trying to find a way for it. First of all, I can develop a command like "convert all of the icons", it's simple but I don't know how can I specify a bounding box. I need more research about it.

and also I'm developing the new version of this plugin, I will try to add svg support like svg-sprite export, import one svg icon, merge svg icons... blah blah blah 🎉 first I need to finish my roadmap 😁

Cheers

**Comment by joshmtucker** [comment]
Exciting! Looking forward to what's ahead. Hit me up if I can help out in any way!

So, this is just me brainstorming here, but how would this approach fly (unclear on the API available):

1. Do you know the font size of that layer?
2. Can you convert said font layer to outlines? 
3. Can you create a layer with the dimensions of font size x font size (square)
4. Can you set the index to be below the layer you converted to outlines?

If you knew the font size and could create a layer using the font size as the dimensions, then you'd have your base. Not clear on converting to outlines.

**Comment by keremciu** [comment]
yep, I'm developing that now :)

Can you send me a screencast about what're you doing today for this example in Sketch?

the command will do in my mind:

- create a base layer like fontsizeXfontsize
- convert icon font to outlines
- group them (icon and base layer)

and then is that a nice way to share? 

and also I can create an another command:

- create a page "icon-font outlines"
- find all icons in the current page
- run the first command for every icon
- paste them to new page("icon-font outlines")

**Comment by keremciu** [comment]
hello @joshmtucker can you give me your e-mail address?

I'm developing this but I need to sure about something maybe we can discuss on my development version?

**Comment by keremciu** [comment]
You can find my solution about this issue, I will publish it after my tests

![demo][demo-image]

[demo-image]: http://g.recordit.co/TU3az70acC.gif

**Comment by keremciu** [comment]
@joshmtucker I've published the new version, do not forget to export your font-bundle

**Comment by joshmtucker** [comment]
Hey! Sorry for the delay, week was crazy! This looks great, I'll test it out and let you know. You rock!

**Comment by keremciu** [comment]
New version has all features about converting :)

@joshmtucker you can try the new version of it

**Comment by joshmtucker** [comment]
Hey there! Sorry for the delay. When I try to convert, it appears to run but nothing happens. Any thoughts on what could be happening?

**Comment by keremciu** [comment]
@joshmtucker I will share the new version this week, it will be stable version of the plugin

**Comment by joshmtucker** [comment]
Awesome!

**Comment by keremciu** [comment]
@joshmtucker if you reinstall the plugin, this version is working for convert now :)

**Comment by joshmtucker** [comment]
Works great! Thanks man :).
