### ISSUE TITLE
Search doesn't appear to work for FontAwesome

### ISSUE THREAD

**Issue by nathanharris76** [keremciu/sketch-iconfont#49]
Try searching for 'book' or 'fa-book' - book icon does not appear (video attached) 

[search.mov.zip](https://github.com/keremciu/sketch-iconfont/files/252285/search.mov.zip)

**Comment by keremciu** [comment]
@nathanharris76 it is related with #48 , fontawesome don't have a nice-writen svg file :/ we need to use latest version and their builded svg file need manipulates everytime for naming. maybe I can build "svg-names" solution for only fontawesome, I will think about that
