### ISSUE TITLE
Importing SVG icons broken?

### ISSUE THREAD

**Issue by jaminroe** [keremciu/sketch-iconfont#50]
I just imported a font, with a couple new icons that I've exported from Sketch, and generate an icon font from https://icomoon.io. Those new icons, are now showing up as question mark boxes in the plug-in, in Sketch:

![screen shot 2016-05-11 at 12 50 23 pm](https://cloud.githubusercontent.com/assets/1559447/15189140/3166cd6a-1777-11e6-9018-5290bf5e7b1d.png)

Here's the icon font SVG file and the two icons, that are showing up like that:
[Archive.zip](https://github.com/keremciu/sketch-iconfont/files/259780/Archive.zip)

Thanks!

**Comment by jaminroe** [comment]
Never mind... wasn't clear that I had to install the TTF before using the plug-in. Duplicate of https://github.com/keremciu/sketch-iconfont/issues/43#issuecomment-210577554

**Comment by keremciu** [comment]
@jaminroe I'm trying to develop new version because of that I did not write a nice-detailed article :/
