### ISSUE TITLE
Symbols Issue

### ISSUE THREAD

**Issue by brucejfriedman** [keremciu/sketch-iconfont#51]
I added an icon font (font awesome) directly to the symbols page.  Two problems. 

1 - it landed in the space between symbols and now cannot be removed by any known method.

2 - It now appears on every artboard and cannot be removed by any known method.

**Comment by adam-rodriguez** [comment]
Sounds like a sketch issue. Do you have 3.8 or 3.8.1? They have been having a lot of odd bugs with that update.

**Comment by keremciu** [comment]
hello @brucejfriedman can you give me a screenshot about that?
