### ISSUE TITLE
Plugin wont work with Version 3.8 (29681)

### ISSUE THREAD

**Issue by AlfieElizondo** [keremciu/sketch-iconfont#52]
Uninstalled and reinstaled but the plug-in menú just have 2 options: install budle or install font and either of those do nothing when i select a TTF file or a son.

<img width="581" alt="screen shot 2016-05-19 at 12 13 33 pm" src="https://cloud.githubusercontent.com/assets/6483354/15402699/28a56160-1dbb-11e6-8b0b-a0f51fe9cb74.png">

**Comment by keremciu** [comment]
hello @AlfieElizondo 

it's not related to 3.8 version, I tried now(uninstalled everything and then installed font-bundle) it is working with 3.8.1 but I think your problem could be different

you can download font bundle(https://github.com/keremciu/font-bundles) directory and then you need to select the directory with "Install a Font-Bundle"

If you'd like to add a font, you need to select SVG file of the font

**Comment by AlfieElizondo** [comment]
Thanks man 
Selected the bundle folder and worked like a charm 

Apreciaste the fast response , have a great day , and thanks for such an awesome plugin.


Atte:
Alfredo Elizondo
elizondo.alfie@gmail.com

**Comment by keremciu** [comment]
oh great! I'm so happy to hear them, have a nice day :)
