### ISSUE TITLE
Icon content doesn't change when selecting new icon

### ISSUE THREAD

**Issue by brandorn** [keremciu/sketch-iconfont#54]
Previously-created icons (or any selected text, for that matter) aren't being replaced when I try to change the icon. Neither the selected icon nor the layer name change when I select a new icon from the plugin's dialog window:

![screen shot 2016-05-23 at 11 14 33 am](https://cloud.githubusercontent.com/assets/4594643/15479451/3cb30bae-20ee-11e6-924b-1937c33b2335.png)

I noticed this after the most recent Sketch update (3.8.1), yet it may have been caused by a previous update.

**Comment by brandorn** [comment]
Figured it out!

**Comment by keremciu** [comment]
hello @brandorn so sorry for delaying but I'm happy to solved for you

**Comment by brandorn** [comment]
No problem - I reconfigured the font bundle association, which did the trick. I might've been on an older version of Iconfont. Nice work on the plugin!
