### ISSUE TITLE
only Material Icon is not converted to outline

### ISSUE THREAD

**Issue by sogen** [keremciu/sketch-iconfont#55]
Hi, I added 3 icons from FontAwesome, and 1 icon from Material, but when I use the plugin, only the FontAwesome icons are converted.

![screen shot 2016-06-11 at 4 39 26 pm](https://cloud.githubusercontent.com/assets/2784323/15987603/1bc10996-2ff3-11e6-9ada-a9c51318edea.png)

Using 3.8.3 on Yosemite

**Comment by keremciu** [comment]
@sogen hello, we have new version now https://github.com/keremciu/sketch-iconfont/releases/tag/4.0.1

can you use the new version? its compatible with 3.8.3 but I'm not sure about yosemite :(

**Comment by sogen** [comment]
Hi, version 4.0.1 works 👍 
Great, thanks!
