### ISSUE TITLE
Unable to load all icons 

### ISSUE THREAD

**Issue by marqu3z** [keremciu/sketch-iconfont#56]
I tried to load those icon fonts without the bundle:
 - ionicons
 - font awesome

On OSX El capitan i download each icon set and:
 - Installed the TTF file
 - On sketch i installed the font selecting the SVG file.

Now i'm able to search icons but a lot of them are missing.
Looking at the Font Book app of OSX the icons are present.

An example is the "gear" icon from ionicons.

**Comment by keremciu** [comment]
@marqu3z can you send me a screenshot which I can see your missing icons

and which version are you using?

**Comment by keremciu** [comment]
maybe If you have a chance to share your svg and ttf file, I can try with them

**Comment by marqu3z** [comment]
Icon sets:
[ionicons-2.0.1.zip](https://github.com/keremciu/sketch-iconfont/files/323365/ionicons-2.0.1.zip)
[font-awesome-4.6.3.zip](https://github.com/keremciu/sketch-iconfont/files/323366/font-awesome-4.6.3.zip)

 - Downloaded and installed TTF files on OSX 10.11.5
 - On Sketch 3.8.3 Installed the SVG files 

Once the SVG file is loaded searching the "gear" icon the result is empty. Also looking at the icons grid the icon is not present.

![image](https://cloud.githubusercontent.com/assets/1413476/16194433/dd8c2e72-36f4-11e6-9e7a-903079f4ef86.png)

But looking at the icon list in the Font Book app of OSX the icon is there:

![image](https://cloud.githubusercontent.com/assets/1413476/16194319/43cbb2b2-36f4-11e6-83b3-420b4c06a85a.png)

This is happening with others icons too.

I tried to look at the Ionicons and FontAwesome repo to find some issue regarding the svg files with missing icons, but nothing come up.

**Comment by keremciu** [comment]
because they're using fontsquirrel to build their iconfonts... fontsquirrel is a bad choice to build iconfonts.

you can find the details on https://github.com/FortAwesome/Font-Awesome/issues/9080

You have two option
1. you can use font-bundle then remove other icons (material etc)

2. build ionicon icon font on fontello and you can install it truely then you can search icons
