### ISSUE TITLE
Icons not getting added any longer

### ISSUE THREAD

**Issue by ptribe** [keremciu/sketch-iconfont#57]
First, Thank You! This plugin was working wonderfully for me before. I think a recent sketch update may have caused this plugin to not work. It still opens, shows me a grid of icons, which I can select, but when I hit "+ Add/Change Icon" nothing happens.

**Comment by keremciu** [comment]
hello @ptribe 

thanks for your nice comments, We've new versions of this plugin, you need to uinstall-reinstall it https://github.com/keremciu/sketch-iconfont/releases
