### ISSUE TITLE
Searching for an icon

### ISSUE THREAD

**Issue by jameslavine** [keremciu/sketch-iconfont#59]
I'm just wondering what meta data from the icon your plugin uses for search. For example, if I'm trying to find the [github alt icon](http://fontawesome.io/icon/github-alt/) from Font Awesome, and I'm just having a tough time finding it in the grid insert modal, what do I search to find it?

- If I search "github", nothing comes up.
- If I search "fa-github-alt", nothing comes up.
- If I search "f09b", the icon's unicode, nothing comes up.

In your plugin, this particular icon is named "icon272". Where is that coming from?

Great plugin, by the way! I'd just love to be able to use the search feature.

Thanks,
James

**Comment by keremciu** [comment]
How did you import fontawesome? if you use font-bundle, you can search like github or fa-github

beucase fontawesome is using fontsquirrel to build webfonts and its really bad :)


you can see #48 
https://github.com/keremciu/sketch-iconfont/issues/48
