### ISSUE TITLE
Icon Bundle installation not working on sketch 39.1

### ISSUE THREAD

**Issue by Agrollemund** [keremciu/sketch-iconfont#63]

**Comment by dblooom** [comment]
Same here.

**Comment by keremciu** [comment]
@Agrollemund @dblooom Hey guys, I have new version with new features and It is working with 39.1 but I can't share it now, I hope I will publish the new version weekend, if you need to use it asap, send me an e-mail info@kerem.ws, I will send you that not tested but working version

**Comment by Agrollemund** [comment]
Thanks for the quick answer. Its ok i can wait a while. One comment on the new version could you include keyboard shortcuts as in the old version that was really useful. Love you product

**Comment by GrantMStevens** [comment]
Any update on when you will cut a new version to fix this issue? Appreciate your work on this.

**Comment by keremciu** [comment]
@GrantMStevens Yea, I've fixed this but the new version has new features and for now, the new features have major bugs, that's why I can't share the new version now :/ 

I'd like to share it until Friday

**Comment by Agrollemund** [comment]
Just to add more details in the issue i’m having:

- I try to import a bundle but when i click on import to select the bundles they are greyed out. You can still select hen but nothing is happening.
- Exactly the same issue when you try to import a font

- Today i spend a lot of time to look for the icons i want because you need to type the exact value in the search. I can’t type for example “house” to get the home icon for example.
The use case would be: As a user i want to be able to search icons but not with the exact font awesome syntaxe (fa-lorem)

Thanks a lot for that plugin that makes we win a lot of time.



On 09 Aug 2016, at 15:05, Kerem Sevencan <notifications@github.com<mailto:notifications@github.com>> wrote:


@GrantMStevens<https://github.com/GrantMStevens> Yea, I've fixed this but the new version has new features and for now, the new features have major bugs, that's why I can't share the new version now :/

I'd like to share it until Friday

**Comment by keremciu** [comment]
@Agrollemund @GrantMStevens @dblooom hey guys, I've published the new version please use the new version, I hope you like it :) https://github.com/keremciu/sketch-iconfont/releases/tag/4.4.0
