### ISSUE TITLE
New Material Design font 1.011 is incompatible with the bundle. 

### ISSUE THREAD

**Issue by ridder-mark** [keremciu/sketch-iconfont#64]
![image](https://cloud.githubusercontent.com/assets/11198644/17570846/a883ca1a-5f6b-11e6-8382-27bc0cb3e444.png)

![image](https://cloud.githubusercontent.com/assets/11198644/17570885/cb6b8388-5f6b-11e6-8218-45e87c3e1380.png)

**Comment by keremciu** [comment]
@ridder-mark you need to install material design ttf file from font-bundle directory. https://github.com/keremciu/font-bundles/tree/master/ttf-files

**Comment by ridder-mark** [comment]
hmmm.. that would work.. but the font keeps getting updated with new symbols. Is there a way to update the file. Thanks

**Comment by keremciu** [comment]
@ridder-mark Yea, I'm sorry it is not my choice 😪 I'd like to build it on the right way but It's really a common problem. FontAwesome, MaterialIcons they're using a useless font converters...

When they use a real icon-font converter like fontello, we don't need to convert again that and we will use the main TTF file of the font

By the way, I'm updating font-bundle when they publish a new version of the font

We've too many issues about that like #49 #48
