### ISSUE TITLE
All fonts are gone after installing 4.30 version

### ISSUE THREAD

**Issue by 5dmarkii** [keremciu/sketch-iconfont#65]
I couldn't install any new fonts on 4.0.5 so I decided to install a new version. But after replacing it  with 4.3.0, all my fonts are gone and still cannot install new one. I've tried many times of re-installing and it's in vain.

<img width="678" alt="screen shot 2016-08-15 at 4 20 43 pm" src="https://cloud.githubusercontent.com/assets/3367751/17659524/b4b6274a-6305-11e6-8dcc-b84af82e3dfe.png">

**Comment by keremciu** [comment]
@5dmarkii I will share new version tonight, I hope you can install your fonts after update. Please export your font-bundle first for updating the version of this plugin.

**Comment by azumbrunnen** [comment]
Same here… Everything is broken all of the sudden.

**Comment by azumbrunnen** [comment]
<img width="606" alt="screen shot 2016-08-17 at 10 51 34" src="https://cloud.githubusercontent.com/assets/113188/17730342/9d3bb030-6468-11e6-9e6e-3d146bd82295.png">
All icons are gone since the update :(

**Comment by keremciu** [comment]
@5dmarkii @azumbrunnen because material icons needed to update, you need to reinstall the ttf file of material icons from font-bundle
