### ISSUE TITLE
Can't import font bundles 4.4.0

### ISSUE THREAD

**Issue by Agrollemund** [keremciu/sketch-iconfont#66]
Hi, i just installed the lates update 4.4.0 and i tried to install the font bundle you suggested and it still doesn't work. I attached a screen recording to show you. Am i doing something wrong ?
[screencast.zip](https://github.com/keremciu/sketch-iconfont/files/422468/screencast.zip)

Thanks in advance for your help.

**Comment by keremciu** [comment]
@Agrollemund hello, yep, you're doing wrong that you're selecting bundle folder. you need to parent folder of bundle. 
You can watch the video below
http://recordit.co/2PMTB04Jav

**Comment by Agrollemund** [comment]
Great, thanks a lot


On 17 Aug 2016, at 14:42, Kerem Sevencan <notifications@github.com<mailto:notifications@github.com>> wrote:


@Agrollemund<https://github.com/Agrollemund> hello, yep, you're doing wrong that you're selecting bundle folder. you need to parent folder of bundle.
You can watch the video below
http://recordit.co/2PMTB04Jav
