### ISSUE TITLE
Request: include ionicons icon font

### ISSUE THREAD

**Issue by inmabermejo** [keremciu/sketch-iconfont#7]
Hello from Spain, Kerem :-)
first of all, thank you for this awesome plugin, it is making my life with Sketch even easier.

I'd like to resquest the collection http://ionicons.com/ to be supported if feasible. It contains an interesting set of icons with elegant style.

Best regards!

**Comment by keremciu** [comment]
So thanks about your comments and idea. I've added it, it was easy because it has .json file I hope you like it :)

**Comment by Neema** [comment]
@keremciu  - i feel like there will be a lot of requests for these icon fonts: https://github.com/showcases/icon-fonts

**Comment by keremciu** [comment]
I hope they would be nice but you know we need a different nice way to use more icon-fonts. We'll see :) @Neema @inmabermejo
