### ISSUE TITLE
Can't currently install font bundle 

### ISSUE THREAD

**Issue by eworkflow** [keremciu/sketch-iconfont#70]
*Summary:* I am not sure whether the problem is caused by an obsolete plugin with Sketch 39.1 or by the way it acts under OS 10.11.6 on my rather old iMac. Important: Icon Font plugin was fully operational under earlier versions of Sketch and/or OSX and stopped working after recent updates of and/or OS.

*Steps to Reproduce:* Activating Sketch top menu: Plugins / Icon Font / Install a Font-bundle / Browsing to font files' folder.

*Expected Results* TTF font' files available to Sketch/IconFont file browser.

*Actual Results:* TTF font files show grayed out and are not accessible to Sketch/IconFont file browser. Important: Those TTF files are fully accessible from Finder.

System Info:

Bundle Identifier: com.bohemiancoding.sketch3

Build Version: 39.1

Build Number: 31720

OS Version: 10.11.6

**Comment by keremciu** [comment]
@eworkflow did you select the folder like this? http://recordit.co/2PMTB04Jav

**Comment by eworkflow** [comment]
I was under an impression I did follow the video's instruction. In any case, I repeated it and it worked this time. Thank you.

**Comment by keremciu** [comment]
Oh welcome, I'm happy to hear that, enjoy it 🎉

**Comment by keremciu** [comment]
@eworkflow Oh welcome, I'm happy to hear that, enjoy it 🎉
