### ISSUE TITLE
Updating font doesn'work

### ISSUE THREAD

**Issue by thoomasbro** [keremciu/sketch-iconfont#71]
After creating an icon font via fontello.com or icomoon.io, when updating the font (deleting and reinstalling ttf file in the fontbook and removing/reinstalling the svg font via the plugin installer), it is impossible to see the new icons.
New placeholders appears, either with /u or with a "-".

**Comment by keremciu** [comment]
If you can see new placeholders, you update the svg file, its good but your ttf file is not new, I think it's the main problem.

has your iconfont an id or fontname? it needs to be same as well. Now I can tell only that try again to install ttf file :/

If you'd like to share that, I can try as well and then also delete it :)

info@kerem.ws is my mail adress
