### ISSUE TITLE
Unable to install from SVG

### ISSUE THREAD

**Issue by oskarkrawczyk** [keremciu/sketch-iconfont#72]
I'm having some issues with installing BlackTie from SVG, after import all I get is (TTF is installed):

<img width="799" alt="screen shot 2016-09-09 at 21 49 39" src="https://cloud.githubusercontent.com/assets/34213/18400799/bdfd410e-76d7-11e6-8949-cf7b6e081c47.png">

Also, I'm not quite sure I understand the import window correctly, because what it implies is that I should copy `<i class='fa fa-*****'></i>` to the input above – not sure what's the point this, and if I should change anything here at all.

I'd love to use the plugin but I just can't get it to work with fonts other than from your font-bundle.

Attaching SVG+TTF: [Archive.zip](https://github.com/keremciu/sketch-iconfont/files/464711/Archive.zip)

**Comment by keremciu** [comment]
@oskarkrawczyk hello Oskar, I've updated the plugin for your problem https://github.com/keremciu/sketch-iconfont/releases/tag/4.4.1

The font id which is writing in SVG file is wrong, I handled it with this version I hope it helps you :) Enjoy it

**Comment by oskarkrawczyk** [comment]
@keremciu Awesome, will try it out today. Btw. I think you've forgot to bump the version in `manifest.json` :-)
