### ISSUE TITLE
Can't install FontAwesome, every font appears listed twice

### ISSUE THREAD

**Issue by sogen** [keremciu/sketch-iconfont#73]
Hi, updated to latest version and all the fonts appeared listed twice in Grid Insert: 
In filename and in font name (ie "material" and "Google Material")

So, I removed all the fonts using the Remove menu, 
and now can't reinstall FontAwesome.

**Comment by keremciu** [comment]
Hello @sogen 

it is a hard case to determine the problem :) can you try to remove all fonts from fontbook and plugin and then try to install font-bundle?

**Comment by sogen** [comment]
Hi, fixed it by uninstalling the plugin from Sketch Toolbox. After that it started working again
