### ISSUE TITLE
Update Material-Icon set

### ISSUE THREAD

**Issue by arthur-koenig** [keremciu/sketch-iconfont#74]
When installing the font bundle, the MaterialIcons_Regular.ttf is installed on the user's machine. 
I don't know if the version included in the bundle is outdated, but it created a problem when navigating on websites that use material icons, such as the official Material Icons [website](https://design.google.com/icons/), because sometimes, their css looks for the local file on the user's end before reaching to a host: 

@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  **src: local('Material Icons'), local('MaterialIcons-Regular'),**url(https://fonts.gstatic.com/s/materialicons/v18/........

If your browser finds a version of the Material icon font installed on your machine, it will use it. Problem is, the one available in the iconfont bundle isn't fully recognized by any browser... Could this be resolved by getting the latest MaterialIcon-Regular.ttf version in the bundle? 
Here is a screenshot of the rendering issue on Chrome (same on Firefox)

![79977ae2-f343-11e5-91d9-eaa8e15ea3f9](https://cloud.githubusercontent.com/assets/17574782/18792728/e8d93938-81b7-11e6-9bf0-536afd4f2476.png)

**Comment by keremciu** [comment]
same #68 thanks to creating an issue but we fix that problem before you should delete the materialicon regular font from fontbook and needs to install new font-bundle, please read the discussion on #68 if you have any problem
