### ISSUE TITLE
Does not work with Sketch 41

### ISSUE THREAD

**Issue by evandiamond** [keremciu/sketch-iconfont#76]
Icon Font broke today after the update. No longer imports icons.

**Comment by ohlincik** [comment]
I'm experiencing the same issue. The plugin UI still works normal but when I click on an icon, nothing gets inserted.

**Comment by pagegwood** [comment]
Ditto

**Comment by chenware** [comment]
Blech. Updated to 41, no longer works.

**Comment by vvinhas** [comment]
Same here

**Comment by vincentteng** [comment]
Same issue here, appreciate your work.

**Comment by billstrahlend** [comment]
Same issue here.

**Comment by stevenrkn** [comment]
Plus 1.

**Comment by jesstech** [comment]
Seems `MSColor.colorWithSVGString` was removed in Sketch v41:

http://mail.sketchplugins.com/pipermail/dev_sketchplugins.com/2016-November/003995.html

**Comment by uxandy** [comment]
Terrible timing for me to update Sketch, should have finished my project and then updated. Greatly appreciate your efforts, I hope we see a fix for this soon. I can't live without your plugin kind sir.

**Comment by keremciu** [comment]
@uxandy @jesstech @stevenrkn @billstrahlend @vincentteng @vvinhas @chenware @pagegwood @ohlincik @evandiamond 

Hey guys, I've updated the plugin https://github.com/keremciu/sketch-iconfont/releases/tag/4.5.1

**Comment by chenware** [comment]
Thanks!

**Comment by ohlincik** [comment]
Thanks for taking care of this so quickly! And thank you for all your work on this excellent plugin.

**Comment by pagegwood** [comment]
@keremciu you rock, thank you sir!

**Comment by vincentteng** [comment]
Thank you kind sir!

**Comment by evandiamond** [comment]
You are a rockstar. Thank you!


*Evan*
