### ISSUE TITLE
No icons appear when using grid insert in sketch Version 41 (35326)

### ISSUE THREAD

**Issue by arondius** [keremciu/sketch-iconfont#77]
I'm using version 4.4.2 on Siera, and when I use grid insert (both on text layer and non text layer) doesn't generate an icon.

Any idea what it could be?

**Comment by keremciu** [comment]
I've updated the plugin today https://github.com/keremciu/sketch-iconfont/releases/tag/4.5.1 did you try this one?

**Comment by renandf** [comment]
I was having the same problem and then I installed v4.5.1 as suggested by Kerem. Everything is working well again. Thanks @keremciu

**Comment by twinsant** [comment]
How to update with Sketch Toolbox?

**Comment by twinsant** [comment]
Hmm, I just uninstall/reinstall with Toolbox and Install font bundle again :) It works like a charm

**Comment by arondius** [comment]
@keremciu Yes it's working again. Thanks for making this plugin and the quick fix! 👍
