### ISSUE TITLE
Sketch 41 - The insertion of font icons isn't working since the update

### ISSUE THREAD

**Issue by Agrollemund** [keremciu/sketch-iconfont#78]
Hi :),

I think we need an update in order for your really cool plugin to work with the new sketch version (Sketchapp 41). Right now i can still browse icons as before but when i want to insert one its not working anymore.

I remember that in the old version it was possible to trigger this plugin by using keyboard shortcuts. 
Do you plan to re-introduce that?

**Comment by keremciu** [comment]
Hello @Agrollemund 

#78 #77 duplicated issue
yep, I've updated the plugin yesterday, you can follow updates from twitter.com/keremciu 
https://github.com/keremciu/sketch-iconfont/releases/tag/4.5.1 

we can discuss keyboard shortcuts at gitter.im chat room, I'm trying to build a new version has quick install and keyboard shortcuts, I'll share it soon :)

**Comment by Agrollemund** [comment]
Thanks a lot will do that ;)
