### ISSUE TITLE
Cant insert Icons since Sketch 41

### ISSUE THREAD

**Issue by dethleffson** [keremciu/sketch-iconfont#79]
Good day to you Sir,

your plugin isnt working well since the latest update of Sketch (41). I can browse, search and install new fonts but if im going to add them to my artboard, nothing happens.

Hope you can fix the Issue fast, I love your plugin and at the moment its a natural habbit to work with.

Cheers,
Max

**Comment by keremciu** [comment]
Hello @dethleffson,

so thanks for your nice comments 😊

#78 #77 #76 duplicated issue
yep, I've updated the plugin yesterday, you can follow updates from twitter.com/keremciu 
https://github.com/keremciu/sketch-iconfont/releases/tag/4.5.1

When you update the plugin, it will work with 41, enjoy with it ✌🏻🙃

Cheers,
Kerem
