### ISSUE TITLE
Incompatible with Sketch 41

### ISSUE THREAD

**Issue by legionio** [keremciu/sketch-iconfont#80]
This plugin does not work with Sketch version 41(35326) - it was working prior to the update. When you click on the icon of your choice, it does not inject it into the page. It's almost as if you didn't select an icon at all because nothing happens when you do.

Tested this on two different macbooks and both have the same problem.

**Comment by keremciu** [comment]
Hello @legionio 

#79 #78 #77 #76 duplicated issue
yep, I've updated the plugin yesterday, you can follow updates from twitter.com/keremciu 
https://github.com/keremciu/sketch-iconfont/releases/tag/4.5.1

When you update the plugin, it will work with 41, enjoy with it ✌🏻🙃

Cheers,
Kerem
