### ISSUE TITLE
Clicking icon in grid doesn't insert it

### ISSUE THREAD

**Issue by tzakiel** [keremciu/sketch-iconfont#83]
This used to work but now it doesn't, maybe after upgrading sketch? When I click an icon in the grid, the grid closes but no icon appears in my sketch file or layers.

**Comment by juliat** [comment]
I have the same problem, upgrading didn't affect it (I tried upgrading to see if it would fix this issue).

**Comment by keremciu** [comment]
hello @tzakiel @juliat 

did you install the latest version of plugin?

https://github.com/keremciu/sketch-iconfont/releases/tag/4.5.1
