### ISSUE TITLE
Updating fonts issues

### ISSUE THREAD

**Issue by jaminroe** [keremciu/sketch-iconfont#86]
I wanted to get the latest version of FontAwesome, so I installed the latest .OTF file, and imported the SVG file via the plug-in. Now I see new icons, but there's only about 20 - 30. As you probably know, there's hundreds of icons in FontAwesome.

I used .OTF because in the [font-bundle from here](https://github.com/keremciu/font-bundles), you use the .OTF version for FontAwesome.

Any ideas why this is happening? Thanks!

**Comment by keremciu** [comment]
hello again @jaminroe 

yea because I'm not using their SVG file, I'm always building a new icon-font with fontello.com after fontello process I'm doing the same thing install to FontBook and install SVG to plugin

their font creator is really bad, we can't search an icon if we use their built-in webfonts

I'd like to update font-awesome to 4.7, if you finish that send a PR to font-bundle please

**Comment by jaminroe** [comment]
Ahhhh, okay! I will have to try and figure it out. If I do I'll do a PR.

I think Icomoon has FontAwesome built-in to it! So maybe I can create the icon-font starting there!

If I export the updated bundle, I only get .json files. Do you need me to include (in the commit) something else too? .ttf and .svg right?

**Comment by jaminroe** [comment]
So related to this, I updated my Icomoon font but what happens is I get multiple entries in the menu now. I tried searching through some of the .json files in the plug-ins contents, but didn't see any double entries. Probably something over my head in JS or something:

![image](https://cloud.githubusercontent.com/assets/1559447/21190354/764add5e-c1ef-11e6-99ac-08882b62df62.png)

Also seems that I have to restart Sketch to get the new icons to show up too. Maybe something that can't be helped though.

**Comment by keremciu** [comment]
firstly you need to remove fonts with "Remove a Font" command

<img width="758" alt="screen shot 2016-12-15 at 09 54 17" src="https://cloud.githubusercontent.com/assets/1593488/21214556/77f404ba-c2ac-11e6-8ad4-4e635f5dd431.png">
you should change the name of font like this, you can find the settings button right side of download button

**Comment by jaminroe** [comment]
Ahhhh... so it's caching the name or something. Okay. Well that's a bummer if you want to update the font each time.

I did Remove the font before adding the updated version. I'll try again though, thanks!
