### ISSUE TITLE
Create custom library?

### ISSUE THREAD

**Issue by ross999** [keremciu/sketch-iconfont#9]
I think I can take a bunch of random icons and create my own ttf/otf file. Would be nice to be able to add them in.

Also - I recently found a HUGE icon set called retinaicon.com - They are pay icons but possible in future to add any .ttf/.otf file? I guess similar to above question.

Awesome work btw. Thanks.

**Comment by vitorfernandes** [comment]
yeah, the same issue here! ;)

**Comment by keremciu** [comment]
I'm trying to build a solution for this. but it needs really basic solution. I've made a SVG font upload solution but it's not good. If I can read the installed fonts on os, it will be a good solution. and also I have a lot of ideas to improve this plugin. you can join gitter talks about them. https://gitter.im/keremciu/sketch-iconfont

custom icon font supports and SVG icon exporter are my main objectives now :) I hope I can do them soon.
