### ISSUE TITLE
hlp request

### ISSUE THREAD

**Issue by cegoga** [keremciu/sketch-iconfont#91]
hi, 
i have a problem with the icons in the bundle.
All the icons appears like this...i don't know why..
thanks 🙏
![schermata 2016-12-30 alle 18 02 46](https://cloud.githubusercontent.com/assets/19481039/21569149/9aca9ad4-ceba-11e6-8f2e-21ad83f7ae6b.png)

**Comment by keremciu** [comment]
@cegoga Hey! did you install ttf files to your fontbook? 

you can watch this video http://recordit.co/2PMTB04Jav

**Comment by cegoga** [comment]
yes i did install so when i try to install it appears like this.. i don't know if it's normal.. thanks
![schermata 2017-01-02 alle 12 19 34](https://cloud.githubusercontent.com/assets/19481039/21588377/51a04c0e-d0e6-11e6-8ab7-4141596dc155.png)
