### ISSUE TITLE
Had plugin, updated, now won't load the Grid pane

### ISSUE THREAD

**Issue by jdille** [keremciu/sketch-iconfont#93]
Hey there,

I had the plugin installed. I updated my "material" font. I got the footnote notification that I was ready to grid insert, but when I go through the menu and click, the pane doesn't appear so I can't insert any icons. Am I doing something wrong?

I double-checked I have everything in order, and I restarted Sketch and my machine several times. Any input would be appreciated!

In the plugin folder, fonts installed, and font-bundles-master used:
![image](https://cloud.githubusercontent.com/assets/24947416/21703045/1a87db8a-d364-11e6-8fb8-39c9b663acbe.png)

Thanks!

**Comment by keremciu** [comment]
@jdille hello, it looks so clear,

are you using Anima App - Auto Layout plugin?

You should update it
https://twitter.com/AnimaApp/status/816711298482372615

**Comment by jdille** [comment]
That fixed it 👍 

Thanks!
