### ISSUE TITLE
Load more icon fonts

### ISSUE THREAD

**Issue by edge0703** [keremciu/sketch-iconfont#94]
A while ago I asked for a description on how to import more icon fonts, for example from Icomoon, but unfortunately, I didn't hear back from you so far. Also, the related thread seems to be gone. Could you please provide such instructions?

**Comment by keremciu** [comment]
@edge0703 so sorry about huge delaying... I changed my job and it took too much personal time, I have a new version and a video on my pc but I can't share them because of time problems 😓 but I'd like to share them as soon as possible

**Comment by edge0703** [comment]
Totally appreciate your efforts and understand that you may haven't time at the moment. Take your time, I just wondered what happened to the video, as it already seemed to done.

**Comment by keremciu** [comment]
@edge0703 hello man, new version of plugin and important video has more work... but I took a video to explain how you can import a custom icon-font http://recordit.co/wy5ihqjPml

**Comment by keremciu** [comment]
if you'd like to have more, #95 has another video
