### ISSUE TITLE
Office 365 icons font

### ISSUE THREAD

**Issue by mlp73** [keremciu/sketch-iconfont#95]
Hey! Great plugin!
Any idea why Office 365 icons won't appear properly through the plugin?
I tried both by adding a simple SVG, and by adding the reference to a complete font bundle. Both without success, icons appear as '-' and '?'
The official font file can be downloaded at: http://o365icons.cloudapp.net/
Any help is much appreciated

**Comment by keremciu** [comment]
hello @mlp73 

I will try this one tonight, I hope I can fix it immediately

**Comment by mlp73** [comment]
Hei! Any feedback about that one? I experience the exact same problem with fabricmdl2icons which is also an official Microsoft Font for Fabric UI.

**Comment by keremciu** [comment]
@mlp73 hello man, I took a video about this problem, I used fontello.com to explain how you can import a new builded icon-font http://recordit.co/wy5ihqjPml

**Comment by mlp73** [comment]
Well, As mentioned in my original post 

> I tried both by adding a simple SVG, and by adding the reference to a complete font bundle. Both without success, icons appear as '-' and '?'.

Your example shows how to gather svg icons into one font and then importing it. I am not in this case as I am already using official icon font provided by Microsoft.
I experienced first the issue with office365icons (ttf and svg), and now again with fabricmdl2icons (only ttf provided)

**Comment by mlp73** [comment]
Here is an example with office365icons. AFTER being converted through Fontello:

<img width="613" alt="skjermbilde 2017-01-19 kl 08 12 03" src="https://cloud.githubusercontent.com/assets/5936956/22097007/077d6396-de1f-11e6-8eb8-ea48c62e0933.png">

**Comment by keremciu** [comment]
@mlp73 I will take a video for your case at night. I think you missed something, maybe you did not write any font-name to your iconfont?

**Comment by keremciu** [comment]
@mlp73 I took it, I hope you can do that with this video. I did everything so clearly, you can understand your problem with that. http://recordit.co/Eiu2fpyu0B

**Comment by benedikt-d** [comment]
Website seems to be down.

**Comment by keremciu** [comment]
@benedikt-d recordit.co?

**Comment by benedikt-d** [comment]
@keremciu http://o365icons.cloudapp.net/
