### ISSUE TITLE
I love this plugin but it seems to be incompatible with the new version of Sketch!

### ISSUE THREAD

**Issue by mikeballz** [keremciu/sketch-iconfont#96]
I use icon font so much (THANK YOU GUYS!) that it's the only thing preventing me from updating to the new version of Sketch v43.

I would love an update!

Feel free to reach out if you need to test a beta, I'd be happy to help out in that regard.

Thanks for an awesome plugin!

M

**Comment by keremciu** [comment]
@mikeballz 

Hello, 

thanks for your nice comments,
where can I find version 43 of Sketch? 

Cheers

**Comment by mikeballz** [comment]
Whoops, I'm sorry, I meant to say *41.2*! For some reason I was convinced
the latest update was 43.

But I think the font plugin stopped working for me in the last two versions
(whenever Bohemian decided to change the app icon and made some of the
icons in the top bar a much brighter neon green)

Hope this helps!

And if by some chance the plugin SHOULD work in 41.2, I will happily give
it another shot! But i've reverted back to 40.3 for the time being because
I know it works in that version.

Thanks again for making such a great tool!

MB

**Comment by keremciu** [comment]
@mikeballz 

thanks again,

Normally it is working with 41.2

I think you should reinstall the plugin
https://github.com/keremciu/sketch-iconfont/releases/tag/4.5.1

if you'd like to read we have related issues below:
#92 #88 #80 #79 #78 #77 #76 duplicated issue

also I'll share a new video and new version of plugin soon, please stay get in touch 😇 if you'd like to follow, I will tell to my followers on twitter.com/keremciu

**Comment by mikeballz** [comment]
Awesome, I will give it a shot! Thanks for reaching out personally and
addressing my issue. I will continue to spread the word about the plugin :)

M
