### ISSUE TITLE
Unable to correctly import the latest Material Icons in SVG format

### ISSUE THREAD

**Issue by CircuitCoder** [keremciu/sketch-iconfont#97]
I just downloaded the latest Material Icons files from [its repo](https://github.com/google/material-design-icons/tree/master/iconfont) and after I imported the font, it showed up as random characters in the icon grid.

![screen shot 2017-01-20 at 21 11 08](https://cloud.githubusercontent.com/assets/2051572/22150625/fe9bbe6c-df54-11e6-9422-8f981cdd2014.png)

I have installed the TTF and was able to manually type in icon aliases inside a text field to make them displayed correctly. For example, if I type "add" in a text field and select Material Icons as its font family, a plus sign will show up.

I read the code and it seems that the problem occurred because Google used Unicode strings longer than one character for each glyph. Also, they are not fully escaped.

![screen shot 2017-01-20 at 21 15 08](https://cloud.githubusercontent.com/assets/2051572/22150736/ae28afc0-df55-11e6-950c-1da4eecd0912.png)

So is there any workaround to this? I have just started using this plugin and it was extremely helpful. It's just that I cannot use Material Icons which is a little bit annoying.

PS. I'm not a native English speaker, so sorry for the bad English.

**Comment by keremciu** [comment]
@CircuitCoder this is an old problem you can find that material-icons problem, you should create an icon-font

http://recordit.co/wy5ihqjPml

**Comment by CircuitCoder** [comment]
That fixed the problem. 👍

Thanks a lot.
