### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by tsalexey544** [keremciu/sketch-iconfont#98]
I click on the icon and get nothing. Using latest sketch version. Old version of iconfont works fine

**Comment by keremciu** [comment]
hello @tsalexey544 are you using auto-layout plugin?

you should update it
https://github.com/keremciu/sketch-iconfont/issues/93

#93 #92 #88 #80 #79 #78 #77 #76 duplicated issue

**Comment by tsalexey544** [comment]
I am using Anima App - Auto Layout plugin and it is up to date. I updated it yesterday.... But it didnt help

**Comment by keremciu** [comment]
@tsalexey544 I'm using sketch version 42. latest version of this plugin and auto layout plugin of anima app, it is working
