### ISSUE TITLE
Question marks instead of fonts

### ISSUE THREAD

**Issue by MincePie** [keremciu/sketch-iconfont#99]
Hello, I'm installing fonts (SVG) files. I can see from your readme that you think the ttf files also need to be installed. I tried that with one of my libraries, however, I still just get a row of buttons that are labelled as question marks instead of the actual font. How do I use this? Thanks

**Comment by keremciu** [comment]
Hello @MincePie ,

Are you using font-bundle or you custom icon-font?

Cheers,

**Comment by MincePie** [comment]
Hi Kerem

I tried to use both. Neither works.

Thanks!


On 25 January 2017 at 8:08:17 pm, Kerem Sevencan (notifications@github.com) wrote:

Hello @MincePie ,

Are you using font-bundle or you custom icon-font?

Cheers,

**Comment by keremciu** [comment]
I've two videos about your problems:


for font font-bundle: http://recordit.co/2PMTB04Jav

for custom icon-font: http://recordit.co/wy5ihqjPml

**Comment by MincePie** [comment]
Thanks - but this didnt work. 

I follow the steps. I don’t get the icons. I note you are incorporating the TTOs rather than the SVGs. I’ve tried both ways - but cant get either to work.



On 26 January 2017 at 8:11:00 pm, Kerem Sevencan (notifications@github.com) wrote:

Closed #99.
